namespace AAEmu.Game.Models.Game.Char
{
    public enum ActabilityType
    {
        Alchemy = 1,
        Construction = 2,
        Cooking = 3,
        Handicrafts = 4,
        Husbandry = 5,
        Farming = 6,
        Fishing = 7,
        Logging = 8,
        Gathering = 9,
        Machining = 10,
        Metalwork = 11,
        Printing = 12,
        Mining = 13,
        Masonry = 14,
        Tailoring = 15,
        Leatherwork = 16,
        Weaponry = 17,
        Carpentry = 18,
        Quest = 19,
        Larceny = 20,
        NuianLanguage = 21,
        ElvenLanguage = 22,
        DwarvenLanguage = 23,
        FaerieLanguage = 24,
        HaraniLanguage = 25,
        FirranLanguage = 26,
        WarbornLanguage = 27,
        ReturnedLanguage = 28,
        NuiaContinentDialect = 29,
        HaranyaContinentDialect = 30,
        Commerce = 31,
        CommemorativeEvent = 32,
        Artistry = 33,
        Exploration = 34
    }
}
