<Project>
  <PropertyGroup>
    <Company>AAEmu</Company>
    <Copyright>Copyright (c) 2019 - 2026 the AAEmu contributors</Copyright>
    <TargetFramework>net10.0</TargetFramework>
    <VersionPrefix>10.0.2.13</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
