namespace AAEmu.Game.Models.Game.Quests.Static
{
    public enum QuestStatusFailed
    {
        Succssed = 0,
        AlreadyHave = 1,
        InvalidQuest = 2,
        PlayerNotFound = 3,
        InvalidCharacter = 4,
        CantSupplyQuestItem = 5,
        MaybeQuestListFull = 6,
        InvalidNpcOrQuest = 7,
        InvalidRequestForNpc = 8,
        UnitRequirementCheck = 9,
        InvalidRewardSelection = 10,
        CantSupplyRewards = 11,
        InvalidQuestStatus = 12,
        RemoveQuestItemFail = 13,
        InvalidQuestObjective = 14,
        InvalidQuestObjective_index = 15,
        WrongAnswerForPlayerChoice = 16,
        PrecedentObjectiveIsNotCompleted = 17,
        InvalidNpc = 18,
        InvalidDoodad = 19,
        TooFarAwayToInteractWith = 20,
        UpdateFailed = 21,
        NotProgressing = 22,
        BagFull = 23,
        ItemRequired = 24,
        LevelNotMatch = 25,
        GainedItemIsNotMatch = 26,
        AlreadyCompleted = 27,
        BackpackOccupied = 28,
        CantSupplyMoney = 29,
        CantAcceptByFatigue = 30,
        DailyLimit = 31,
        NoMateItemInTheBag = 32,
        NeedToMateSummon = 33,
        NotEnoughMate_level = 34,
        MateEquipmentsAreNotEmpty = 35,
        PlayerTrade = 36,
        GameSchedule = 37
    }
}
