namespace AAEmu.Game.Models.Game.Skills.Static;

#pragma warning disable IDE0079 // Remove unnecessary suppression
#pragma warning disable CA1069 // Enums should not be duplicated

/// <summary>
/// Skill result byte values used by the 10.0.2.13 client.
/// Recovered from the client's SkillResult-to-symbol switch.
/// </summary>
public enum SkillResult : byte
{
    Success = 0x0,
    Failure = 0x1,
    SourceDied = 0x2,
    SourceAlive = 0x3,
    TargetDied = 0x4,
    TargetDestroyed = 0x5,
    TargetAlive = 0x6,
    OnCasting = 0x7,
    CooldownTime = 0x8,
    NoTarget = 0x9,
    LackHealth = 0xA,
    LackMana = 0xB,
    Obstacle = 0xC,
    OutofHeight = 0xD,
    TooCloseRange = 0xE,
    TooFarRange = 0xF,
    OutofAngle = 0x10,
    CannotCastInCombat = 0x11,
    CannotCastWhileMoving = 0x12,
    CannotCastInStun = 0x13,
    CannotCastWhileWalking = 0x14,
    CannotCastInSwimming = 0x15,
    BlankMinded = 0x16,
    Silence = 0x17,
    Crippled = 0x18,
    CannotCastInChanneling = 0x19,
    CannotCastInPrison = 0x1A,
    NeedStealth = 0x1B,
    NeedNocombatTarget = 0x1C,
    TargetImmune = 0x1D,
    InvalidSkill = 0x1E,
    InactiveAbility = 0x1F,
    NotEnoughAbilityLevel = 0x20,
    InvalidSource = 0x21,
    InvalidTarget = 0x22,
    InvalidLocation = 0x23,
    NeedReagent = 0x24,
    ItemLocked = 0x25,
    NeedMoney = 0x26,
    NeedLaborPower = 0x27,
    SourceIsHanging = 0x28,
    SourceIsRiding = 0x29,
    HigherBuff = 0x2A,
    NotPvpArea = 0x2B,
    NotNow = 0x2C,
    NoPerm = 0x2D,
    BagFull = 0x2E,
    ProtectedFaction = 0x2F,
    ProtectedLevel = 0x30,
    UnitReqsOrFail = 0x31,
    SkillReqFail = 0x32,
    BackpackOccupied = 0x33,
    ObstacleForSpawnDoodad = 0x34,
    CannotSpawnDoodadInHouse = 0x35,
    CannotUseForSelf = 0x36,
    NotPreoccupied = 0x37,
    NotMyNpc = 0x38,
    NotCheckedSecondPass = 0x39,
    ZoneBanned = 0x3A,
    InvalidGradeEnchantSupportItem = 0x3B,
    ItemSecured = 0x3C,
    InvalidAccountAttribute = 0x3D,
    FestivalZone = 0x3E,
    AlreadyOtherPlayerBound = 0x3F,
    UrkUnknown = 0x40, // First unassigned value; the client stringifier returns URK_UNKNOWN.
    CannotUnsummonUnderStunSleepRoot = 0x41,
    LackCombatResource = 0x42,
    LackSourceItemSet = 0x43,
    LackActability = 0x44,
    OnlyDuringSwimming = 0x45,
    UlcAlreadyActivated = 0x46,
    HouseOwner = 0x47,
    SourceCannotUseWhileJumping = 0x48,
    SourceCannotUseWhileLevitating = 0x49,
    UrkStart = 0x49,
    UrkLevel = 0x4A,
    UrkAbility = 0x4B,
    UrkRace = 0x4C,
    UrkGender = 0x4D,
    UrkEquipSlot = 0x4E,
    UrkEquipItem = 0x4F,
    UrkOwnItem = 0x50,
    UrkTrainedSkill = 0x51,
    UrkCombat = 0x52,
    UrkStealth = 0x53,
    UrkHealth = 0x54,
    UrkBuff = 0x55,
    UrkTargetBuff = 0x56,
    UrkTargetCombat = 0x57,
    UrkCanLearnCraft = 0x58,
    UrkDoodadRange = 0x59,
    UrkEquipShield = 0x5A,
    UrkNobuff = 0x5B,
    UrkTargetBuffTag = 0x5C,
    UrkCorpseRange = 0x5D,
    UrkEquipWeaponType = 0x5E,
    UrkTargetHealthLessThan = 0x5F,
    UrkTargetNpc = 0x60,
    UrkTargetDoodad = 0x61,
    UrkEquipRanged = 0x62,
    UrkNoBuffTag = 0x63,
    UrkCompleteQuestContext = 0x64,
    UrkProgressQuestContext = 0x65,
    UrkReadyQuestContext = 0x66,
    UrkTargetNpcGroup = 0x67,
    UrkAreaSphere = 0x68,
    UrkExceptCompleteQuestContext = 0x69,
    UrkPrecompleteQuestContext = 0x6A,
    UrkTargetOwnerType = 0x6B,
    UrkNotUnderWater = 0x6C,
    UrkFactionMatch = 0x6D,
    UrkTod = 0x6E,
    UrkMotherFaction = 0x6F,
    UrkActabilityPoint = 0x70,
    UrkCrimePoint = 0x71,
    UrkHonorPoint = 0x72,
    UrkLivingPoint = 0x73,
    UrkCrimeRecord = 0x74,
    UrkJuryPoint = 0x75,
    UrkSourceOwnerType = 0x76,
    UrkAppellation = 0x77,
    UrkInZone = 0x78,
    UrkOutZone = 0x79,
    UrkVerdictOnly = 0x7A,
    UrkFactionMatchOnly = 0x7B,
    UrkMotherFactionOnly = 0x7C,
    UrkFactionMatchOnlyNot = 0x7D,
    UrkMotherFactionOnlyNot = 0x7E,
    UrkNationMember = 0x7F,
    UrkNationMemberNot = 0x80,
    UrkDominionMemberAtPos = 0x81,
    UrkDominionMemberAtPosNot = 0x82,
    UrkHousing = 0x83,
    UrkHealthMargin = 0x84,
    UrkManaMargin = 0x85,
    UrkLaborPowerMargin = 0x86,
    UrkMaxLevel = 0x88,
    UrkExpeditionOwner = 0x89,
    UrkExpeditionMember = 0x8A,
    UrkExceptProgressQuestContext = 0x8B,
    UrkExceptReadyQuestContext = 0x8C,
    UrkOwnItemNot = 0x8D,
    UrkLessActabilityPoint = 0x8E,
    UrkOwnQuestItemGroup = 0x8F,
    UrkLeadershipTotal = 0x90,
    UrkLeadershipCurrent = 0x91,
    UrkHero = 0x92,
    UrkNotHero = 0x93,
    UrkOwnItemCount = 0x94,
    UrkHouse = 0x96,
    UrkHouseOnly = 0x97,
    UrkDecoLimitExpanded = 0x98,
    UrkNotExpandable = 0x99,
    UrkDoodadTargetFriendly = 0x9A,
    UrkDoodadTargetHostile = 0x9B,
    UrkDominionMember = 0x9C,
    UrkDominionMemberNot = 0x9D,
    UrkCannotUseBuildingHouse = 0x9E,
    UrkTargetNoBuffTag = 0x9F,
    UrkTargetNoBuffTagNoTarget = 0xA0,
    UrkTargetManaLessThan = 0xA4,
    UrkTargetManaMoreThan = 0xA5,
    UrkTargetHealthMoreThan = 0xA6,
    UrkBuffTag = 0xA7,
    UrkFamilyRole = 0xA8,
    UrkLaborPowerMarginLocal = 0xA9,
    UrkHeirLevel = 0xAA,
    UrkInZoneGroup = 0xAB,
    UrkSkillCooldown = 0xAC,
    UrkUnderWater = 0xAD,
    UrkOwnAppellation = 0xAE,
    UrkEquipAppellation = 0xAF,
    UrkEmptySlotInventory = 0xB0,
    UrkFullRechargedLaborPower = 0xB1,
    UrkExpeditionMemberNot = 0xB2,
    UrkPirateMemberLimit = 0xB3,
    UrkAchievementComplete = 0xB4,
    UrkTargetItemTag = 0xB5,
    UrkNoTargetItemTag = 0xB6,
    UrkDual = 0xB7,
    UrkNoDual = 0xB8,
    UrkExpeditionBattle = 0xB9,
    UrkNoExpeditionBattle = 0xBA,
    UrkNotInHousingArea = 0xBB,
    UrkDominionCountMore = 0xBC,
    UrkDominionCountLess = 0xBD,
    UrkPremiumArchePass = 0xBE,
    UrkEnableArchePass = 0xBF,
    UrkGearScore = 0xC0,
    UrkConflictZoneState = 0xC1,
    UrkItemElementEvolvingExp = 0xC2,
    UrkNeedUlcActivate = 0xC3,
    UrkCannotUseByUlcActivate = 0xC4,
    UrkItemLookChangeMapping = 0xC5,
    UrkEnableArchePassWithType = 0xC6,
    UrkCombatResource = 0xC7,
    UrkAddArchePassPoint = 0xC8,
    UrkTowerDefStep = 0xC9,
    UrkSourceHealthLessThan = 0xCA,
    UrkSourceHealthMoreThan = 0xCB,
}

// ReSharper disable InconsistentNaming
/// <summary>
/// Internally used enum for generating SkillResults, do not pass directly to the client
/// </summary>
public enum SkillResultKeys
{
    // NOTE: do not edit the formatting or case of these enums
    ok,
    skill_failure,
    skill_source_died,
    skill_source_alive,
    skill_target_died,
    skill_target_destroyed,
    skill_target_alive,
    skill_on_casting,
    skill_cooldown_time,
    skill_no_target,
    skill_lack_health,
    skill_lack_mana,
    skill_obstacle,
    skill_outof_height,
    skill_too_close_range,
    skill_too_far_range,
    skill_outof_angle,
    skill_cannot_cast_in_combat,
    skill_cannot_cast_while_moving,
    skill_cannot_cast_in_stun,
    skill_cannot_cast_while_walking,
    skill_cannot_cast_in_swimming,
    skill_blank_minded,
    skill_silence,
    skill_crippled,
    skill_cannot_cast_in_channeling,
    skill_cannot_cast_in_prison,
    skill_need_stealth,
    skill_need_nocombat_target,
    skill_target_immune,
    skill_invalid_skill,
    skill_inactive_ability,
    skill_not_enough_ability_level,
    skill_invalid_source,
    skill_invalid_target,
    skill_invalid_location,
    skill_need_reagent,
    skill_item_locked,
    skill_need_money,
    skill_need_labor_power,
    skill_source_is_hanging,
    skill_source_is_riding,
    skill_higher_buff,
    skill_not_pvp_area,
    skill_not_now,
    skill_no_perm,
    skill_bag_full,
    skill_protected_faction,
    skill_protected_level,
    skill_unit_reqs_or_fail,
    backpack_occupied,
    skill_obstacle_for_spawn_doodad,
    skill_cannot_spawn_doodad_in_house,
    skill_cannot_use_for_self,
    skill_not_preoccupied,
    skill_not_my_npc,
    skill_not_checked_second_pass,
    // SKILL_CANNOT_USE_HERE,
    skill_invalid_grade_enchant_support_item,
    skill_check_character_p_stat_min,
    skill_check_character_p_stat_max,
    skill_invalid_account_attribute,
    skill_urk_level,
    skill_urk_ability,
    skill_urk_race,
    skill_urk_gender,
    skill_urk_equip_slot,
    skill_urk_equip_item,
    skill_urk_own_item,
    skill_urk_trained_skill,
    skill_urk_combat,
    skill_urk_stealth,
    skill_urk_health,
    skill_urk_buff,
    skill_urk_target_buff,
    skill_urk_target_combat,
    skill_urk_can_learn_craft,
    skill_urk_doodad_range,
    skill_urk_equip_shield,
    skill_urk_nobuff,
    skill_urk_target_buff_tag,
    skill_urk_corpse_range,
    skill_urk_equip_weapon_type,
    skill_urk_target_health_less_than,
    skill_urk_target_npc,
    skill_urk_target_doodad,
    skill_urk_equip_ranged,
    skill_urk_no_buff_tag,
    skill_urk_complete_quest_context,
    skill_urk_progress_quest_context,
    skill_urk_ready_quest_context,
    skill_urk_target_npc_group,
    skill_urk_area_sphere,
    skill_urk_except_complete_quest_context,
    skill_urk_precomplete_quest_context,
    skill_urk_target_owner_type,
    skill_urk_not_under_water,
    skill_urk_faction_match,
    skill_urk_tod,
    skill_urk_mother_faction,
    skill_urk_actability_point,
    skill_urk_crime_point,
    skill_urk_honor_point,
    skill_urk_living_point,
    skill_urk_crime_record,
    skill_urk_jury_point,
    skill_urk_source_owner_type,
    skill_urk_appellation,
    skill_urk_in_zone,
    skill_urk_out_zone,
    skill_urk_dominion_owner,
    skill_urk_verdict_only,
    skill_urk_faction_match_only,
    skill_urk_mother_faction_only,
    skill_urk_faction_match_only_not,
    skill_urk_mother_faction_only_not,
    skill_urk_nation_member,
    skill_urk_nation_member_not,
    skill_urk_housing,
    skill_urk_mana_margin,
    skill_urk_labor_power_margin,
    skill_urk_labor_power_margin_local,
    skill_urk_unknown,
    skill_urk_max_level,
    skill_urk_expedition_owner,
    skill_urk_expedition_member,
    skill_urk_except_progress_quest_context,
    skill_urk_except_ready_quest_context,
    skill_urk_own_item_not,
    skill_urk_less_actability_point,
    skill_urk_own_quest_item_group,
    skill_urk_house,
    skill_urk_house_only,
    skill_urk_doodad_target_hostile,
    skill_urk_target_nobuff_tag,
    skill_urk_target_nobuff_tag_no_target,
    skill_urk_buff_tag,
    skill_urk_under_water,
    skill_urk_own_appellation,
    skill_urk_equip_appellation,
    skill_urk_empty_slot_inventory,
    skill_urk_heir_level,
    skill_urk_in_zone_group,
    skill_urk_skill_cooldown,
    skill_urk_full_recharged_labor_power,
    skill_urk_expedition_member_not,
    skill_urk_target_mana_less_than,
    skill_urk_target_mana_more_than,
    skill_urk_target_health_more_than,
    skill_urk_source_health_less_than,
    skill_urk_source_health_more_than,
    skill_urk_family_role,
    skill_urk_own_item_count,
    skill_urk_not_in_housing_area,
    skill_urk_dual,
    skill_urk_no_dual,
    skill_urk_combat_resource,
    skill_urk_target_item_tag,
    skill_urk_no_target_item_tag,
    skill_urk_need_ulc_activate,
    skill_urk_cannot_use_by_ulc_activate,
    // Appended, not inserted: these values are internal - SkillResultErrorKeyToId maps them to the
    // SkillResult codes that actually go on the wire - but the enum is implicitly numbered, so anything
    // added in the middle would renumber every key after it.
    skill_urk_hero,
    skill_urk_not_hero,
}
// ReSharper restore InconsistentNaming

/// <summary>
/// Helper class to generate skill result error messages
/// </summary>
public static class SkillResultHelper
{

    public static SkillResult SkillResultErrorKeyToId(SkillResultKeys key)
    {
        return key switch
        {
            SkillResultKeys.ok => SkillResult.Success,
            SkillResultKeys.skill_failure => SkillResult.Failure,
            SkillResultKeys.skill_source_died => SkillResult.SourceDied,
            SkillResultKeys.skill_source_alive => SkillResult.SourceAlive,
            SkillResultKeys.skill_target_died => SkillResult.TargetDied,
            SkillResultKeys.skill_target_destroyed => SkillResult.TargetDestroyed,
            SkillResultKeys.skill_target_alive => SkillResult.TargetAlive,
            SkillResultKeys.skill_on_casting => SkillResult.OnCasting,
            SkillResultKeys.skill_cooldown_time => SkillResult.CooldownTime,
            SkillResultKeys.skill_no_target => SkillResult.NoTarget,
            SkillResultKeys.skill_lack_health => SkillResult.LackHealth,
            SkillResultKeys.skill_lack_mana => SkillResult.LackMana,
            SkillResultKeys.skill_obstacle => SkillResult.Obstacle,
            SkillResultKeys.skill_outof_height => SkillResult.OutofHeight,
            SkillResultKeys.skill_too_close_range => SkillResult.TooCloseRange,
            SkillResultKeys.skill_too_far_range => SkillResult.TooFarRange,
            SkillResultKeys.skill_outof_angle => SkillResult.OutofAngle,
            SkillResultKeys.skill_cannot_cast_in_combat => SkillResult.CannotCastInCombat,
            SkillResultKeys.skill_cannot_cast_while_moving => SkillResult.CannotCastWhileMoving,
            SkillResultKeys.skill_cannot_cast_in_stun => SkillResult.CannotCastInStun,
            SkillResultKeys.skill_cannot_cast_while_walking => SkillResult.CannotCastWhileWalking,
            SkillResultKeys.skill_cannot_cast_in_swimming => SkillResult.CannotCastInSwimming,
            SkillResultKeys.skill_blank_minded => SkillResult.BlankMinded,
            SkillResultKeys.skill_silence => SkillResult.Silence,
            SkillResultKeys.skill_crippled => SkillResult.Crippled,
            SkillResultKeys.skill_cannot_cast_in_channeling => SkillResult.CannotCastInChanneling,
            SkillResultKeys.skill_cannot_cast_in_prison => SkillResult.CannotCastInPrison,
            SkillResultKeys.skill_need_stealth => SkillResult.NeedStealth,
            SkillResultKeys.skill_need_nocombat_target => SkillResult.NeedNocombatTarget,
            SkillResultKeys.skill_target_immune => SkillResult.TargetImmune,
            SkillResultKeys.skill_invalid_skill => SkillResult.InvalidSkill,
            SkillResultKeys.skill_inactive_ability => SkillResult.InactiveAbility,
            SkillResultKeys.skill_not_enough_ability_level => SkillResult.NotEnoughAbilityLevel,
            SkillResultKeys.skill_invalid_source => SkillResult.InvalidSource,
            SkillResultKeys.skill_invalid_target => SkillResult.InvalidTarget,
            SkillResultKeys.skill_invalid_location => SkillResult.InvalidLocation,
            SkillResultKeys.skill_need_reagent => SkillResult.NeedReagent,
            SkillResultKeys.skill_item_locked => SkillResult.ItemLocked,
            SkillResultKeys.skill_need_money => SkillResult.NeedMoney,
            SkillResultKeys.skill_need_labor_power => SkillResult.NeedLaborPower,
            SkillResultKeys.skill_source_is_hanging => SkillResult.SourceIsHanging,
            SkillResultKeys.skill_source_is_riding => SkillResult.SourceIsRiding,
            SkillResultKeys.skill_higher_buff => SkillResult.HigherBuff,
            SkillResultKeys.skill_not_pvp_area => SkillResult.NotPvpArea,
            SkillResultKeys.skill_not_now => SkillResult.NotNow,
            SkillResultKeys.skill_no_perm => SkillResult.NoPerm,
            SkillResultKeys.skill_bag_full => SkillResult.BagFull,
            SkillResultKeys.skill_protected_faction => SkillResult.ProtectedFaction,
            SkillResultKeys.skill_protected_level => SkillResult.ProtectedLevel,
            SkillResultKeys.skill_unit_reqs_or_fail => SkillResult.UnitReqsOrFail,
            SkillResultKeys.backpack_occupied => SkillResult.BackpackOccupied,
            SkillResultKeys.skill_obstacle_for_spawn_doodad => SkillResult.ObstacleForSpawnDoodad,
            SkillResultKeys.skill_cannot_spawn_doodad_in_house => SkillResult.CannotSpawnDoodadInHouse,
            SkillResultKeys.skill_cannot_use_for_self => SkillResult.CannotUseForSelf,
            SkillResultKeys.skill_not_preoccupied => SkillResult.NotPreoccupied,
            SkillResultKeys.skill_not_my_npc => SkillResult.NotMyNpc,
            SkillResultKeys.skill_not_checked_second_pass => SkillResult.NotCheckedSecondPass,
            SkillResultKeys.skill_invalid_grade_enchant_support_item => SkillResult.InvalidGradeEnchantSupportItem,
            SkillResultKeys.skill_invalid_account_attribute => SkillResult.InvalidAccountAttribute,
            SkillResultKeys.skill_urk_level => SkillResult.UrkLevel,
            SkillResultKeys.skill_urk_ability => SkillResult.UrkAbility,
            SkillResultKeys.skill_urk_race => SkillResult.UrkRace,
            SkillResultKeys.skill_urk_gender => SkillResult.UrkGender,
            SkillResultKeys.skill_urk_equip_slot => SkillResult.UrkEquipSlot,
            SkillResultKeys.skill_urk_equip_item => SkillResult.UrkEquipItem,
            SkillResultKeys.skill_urk_own_item => SkillResult.UrkOwnItem,
            SkillResultKeys.skill_urk_trained_skill => SkillResult.UrkTrainedSkill,
            SkillResultKeys.skill_urk_combat => SkillResult.UrkCombat,
            SkillResultKeys.skill_urk_stealth => SkillResult.UrkStealth,
            SkillResultKeys.skill_urk_health => SkillResult.UrkHealth,
            SkillResultKeys.skill_urk_buff => SkillResult.UrkBuff,
            SkillResultKeys.skill_urk_target_buff => SkillResult.UrkTargetBuff,
            SkillResultKeys.skill_urk_target_combat => SkillResult.UrkTargetCombat,
            SkillResultKeys.skill_urk_can_learn_craft => SkillResult.UrkCanLearnCraft,
            SkillResultKeys.skill_urk_doodad_range => SkillResult.UrkDoodadRange,
            SkillResultKeys.skill_urk_equip_shield => SkillResult.UrkEquipShield,
            SkillResultKeys.skill_urk_nobuff => SkillResult.UrkNobuff,
            SkillResultKeys.skill_urk_target_buff_tag => SkillResult.UrkTargetBuffTag,
            SkillResultKeys.skill_urk_corpse_range => SkillResult.UrkCorpseRange,
            SkillResultKeys.skill_urk_equip_weapon_type => SkillResult.UrkEquipWeaponType,
            SkillResultKeys.skill_urk_target_health_less_than => SkillResult.UrkTargetHealthLessThan,
            SkillResultKeys.skill_urk_target_npc => SkillResult.UrkTargetNpc,
            SkillResultKeys.skill_urk_target_doodad => SkillResult.UrkTargetDoodad,
            SkillResultKeys.skill_urk_equip_ranged => SkillResult.UrkEquipRanged,
            SkillResultKeys.skill_urk_no_buff_tag => SkillResult.UrkNoBuffTag,
            SkillResultKeys.skill_urk_complete_quest_context => SkillResult.UrkCompleteQuestContext,
            SkillResultKeys.skill_urk_progress_quest_context => SkillResult.UrkProgressQuestContext,
            SkillResultKeys.skill_urk_ready_quest_context => SkillResult.UrkReadyQuestContext,
            SkillResultKeys.skill_urk_target_npc_group => SkillResult.UrkTargetNpcGroup,
            SkillResultKeys.skill_urk_area_sphere => SkillResult.UrkAreaSphere,
            SkillResultKeys.skill_urk_except_complete_quest_context => SkillResult.UrkExceptCompleteQuestContext,
            SkillResultKeys.skill_urk_precomplete_quest_context => SkillResult.UrkPrecompleteQuestContext,
            SkillResultKeys.skill_urk_target_owner_type => SkillResult.UrkTargetOwnerType,
            SkillResultKeys.skill_urk_not_under_water => SkillResult.UrkNotUnderWater,
            SkillResultKeys.skill_urk_faction_match => SkillResult.UrkFactionMatch,
            SkillResultKeys.skill_urk_tod => SkillResult.UrkTod,
            SkillResultKeys.skill_urk_mother_faction => SkillResult.UrkMotherFaction,
            SkillResultKeys.skill_urk_actability_point => SkillResult.UrkActabilityPoint,
            SkillResultKeys.skill_urk_crime_point => SkillResult.UrkCrimePoint,
            SkillResultKeys.skill_urk_honor_point => SkillResult.UrkHonorPoint,
            SkillResultKeys.skill_urk_living_point => SkillResult.UrkLivingPoint,
            SkillResultKeys.skill_urk_crime_record => SkillResult.UrkCrimeRecord,
            SkillResultKeys.skill_urk_jury_point => SkillResult.UrkJuryPoint,
            SkillResultKeys.skill_urk_source_owner_type => SkillResult.UrkSourceOwnerType,
            SkillResultKeys.skill_urk_appellation => SkillResult.UrkAppellation,
            SkillResultKeys.skill_urk_in_zone => SkillResult.UrkInZone,
            SkillResultKeys.skill_urk_out_zone => SkillResult.UrkOutZone,
            SkillResultKeys.skill_urk_verdict_only => SkillResult.UrkVerdictOnly,
            SkillResultKeys.skill_urk_faction_match_only => SkillResult.UrkFactionMatchOnly,
            SkillResultKeys.skill_urk_mother_faction_only => SkillResult.UrkMotherFactionOnly,
            SkillResultKeys.skill_urk_faction_match_only_not => SkillResult.UrkFactionMatchOnlyNot,
            SkillResultKeys.skill_urk_mother_faction_only_not => SkillResult.UrkMotherFactionOnlyNot,
            SkillResultKeys.skill_urk_nation_member => SkillResult.UrkNationMember,
            SkillResultKeys.skill_urk_nation_member_not => SkillResult.UrkNationMemberNot,
            SkillResultKeys.skill_urk_housing => SkillResult.UrkHousing,
            SkillResultKeys.skill_urk_mana_margin => SkillResult.UrkManaMargin,
            SkillResultKeys.skill_urk_labor_power_margin => SkillResult.UrkLaborPowerMargin,
            SkillResultKeys.skill_urk_labor_power_margin_local => SkillResult.UrkLaborPowerMarginLocal,
            SkillResultKeys.skill_urk_unknown => SkillResult.UrkUnknown,
            SkillResultKeys.skill_urk_max_level => SkillResult.UrkMaxLevel,
            SkillResultKeys.skill_urk_expedition_owner => SkillResult.UrkExpeditionOwner,
            SkillResultKeys.skill_urk_expedition_member => SkillResult.UrkExpeditionMember,
            SkillResultKeys.skill_urk_except_progress_quest_context => SkillResult.UrkExceptProgressQuestContext,
            SkillResultKeys.skill_urk_except_ready_quest_context => SkillResult.UrkExceptReadyQuestContext,
            SkillResultKeys.skill_urk_own_item_not => SkillResult.UrkOwnItemNot,
            SkillResultKeys.skill_urk_less_actability_point => SkillResult.UrkLessActabilityPoint,
            SkillResultKeys.skill_urk_own_quest_item_group => SkillResult.UrkOwnQuestItemGroup,
            SkillResultKeys.skill_urk_house => SkillResult.UrkHouse,
            SkillResultKeys.skill_urk_house_only => SkillResult.UrkHouseOnly,
            SkillResultKeys.skill_urk_doodad_target_hostile => SkillResult.UrkDoodadTargetHostile,
            SkillResultKeys.skill_urk_target_nobuff_tag => SkillResult.UrkTargetNoBuffTag,
            SkillResultKeys.skill_urk_target_nobuff_tag_no_target => SkillResult.UrkTargetNoBuffTagNoTarget,
            SkillResultKeys.skill_urk_buff_tag => SkillResult.UrkBuffTag,
            SkillResultKeys.skill_urk_under_water => SkillResult.UrkUnderWater,
            SkillResultKeys.skill_urk_own_appellation => SkillResult.UrkOwnAppellation,
            SkillResultKeys.skill_urk_equip_appellation => SkillResult.UrkEquipAppellation,
            SkillResultKeys.skill_urk_empty_slot_inventory => SkillResult.UrkEmptySlotInventory,
            SkillResultKeys.skill_urk_heir_level => SkillResult.UrkHeirLevel,
            SkillResultKeys.skill_urk_in_zone_group => SkillResult.UrkInZoneGroup,
            SkillResultKeys.skill_urk_skill_cooldown => SkillResult.UrkSkillCooldown,
            SkillResultKeys.skill_urk_full_recharged_labor_power => SkillResult.UrkFullRechargedLaborPower,
            SkillResultKeys.skill_urk_expedition_member_not => SkillResult.UrkExpeditionMemberNot,
            SkillResultKeys.skill_urk_target_mana_less_than => SkillResult.UrkTargetManaLessThan,
            SkillResultKeys.skill_urk_target_mana_more_than => SkillResult.UrkTargetManaMoreThan,
            SkillResultKeys.skill_urk_target_health_more_than => SkillResult.UrkTargetHealthMoreThan,
            SkillResultKeys.skill_urk_source_health_less_than => SkillResult.UrkSourceHealthLessThan,
            SkillResultKeys.skill_urk_source_health_more_than => SkillResult.UrkSourceHealthMoreThan,
            SkillResultKeys.skill_urk_family_role => SkillResult.UrkFamilyRole,
            SkillResultKeys.skill_urk_own_item_count => SkillResult.UrkOwnItemCount,
            SkillResultKeys.skill_urk_not_in_housing_area => SkillResult.UrkNotInHousingArea,
            SkillResultKeys.skill_urk_dual => SkillResult.UrkDual,
            SkillResultKeys.skill_urk_no_dual => SkillResult.UrkNoDual,
            SkillResultKeys.skill_urk_combat_resource => SkillResult.UrkCombatResource,
            SkillResultKeys.skill_urk_target_item_tag => SkillResult.UrkTargetItemTag,
            SkillResultKeys.skill_urk_no_target_item_tag => SkillResult.UrkNoTargetItemTag,
            SkillResultKeys.skill_urk_need_ulc_activate => SkillResult.UrkNeedUlcActivate,
            SkillResultKeys.skill_urk_cannot_use_by_ulc_activate => SkillResult.UrkCannotUseByUlcActivate,
            SkillResultKeys.skill_urk_hero => SkillResult.UrkHero,
            SkillResultKeys.skill_urk_not_hero => SkillResult.UrkNotHero,
            _ => SkillResult.UrkUnknown
        };
    }

}
