namespace AAEmu.Game.Models.Game.Features
{
    public enum Feature
    {
        //Don't mess with these values, ask the core team for questions.
        //Refer to FeatureSet.GetIndexes to interpret
        siege = 0,
        allowFamilyChanges = 1,
        premium = 4,
        ranking = 36,
        ingamecashshop = 38,
        customsaveload = 40,
        bm_mileage = 43,
        aaPoint = 44,
        itemSecure = 45,
        secondpass = 46,
        slave_customize = 48,
        beautyshopBypass = 52,
        freeLpRaise = 53, //Might not exist for 0.5
        ingameshopSecondpass = 55,
        backpackProfitShare = 56,
        sensitiveOpeartion = 58,
        taxItem = 59,
        achievement = 63,
        dwarfWarborn = 74,
        mailCoolTime = 75,

        //These are different positions in 0.5 for some reason..
        hudAuctionButton = 81,
        auctionPostBuff = 83,
        houseTaxPrepay = 84

        /* 3503 Enum Only
        hudAuctionButton = 89,
        auctionPostBuff = 91,
        itemRepairInBag = 92,
        petOnlyEnchantStone = 93,
        questNpcTag = 94,
        houseTaxPrepay = 95,
        hudBattleFieldButton = 98,
        hudMailBoxButton = 99,
        fastQuestChatBubble = 100,
        todayAssignment = 101,
        forbidTransferChar = 102,
        targetEquipmentWnd = 103,
        indunPortal = 106,
        indunDailyLimit = 110,
        rebuildHouse = 111,
        useTGOS = 112,
        forcePopupTGOS = 113,
        newNameTag = 114,
        reportSpammer = 115,
        hero = 116,
        marketPrice = 117,
        buyPremiuminSelChar = 119,
        expeditionWar = 138,
        freeResurrectionInPlace = 139,
        expeditionLevel = 141,
        itemEvolving = 142,
        useSavedAbilities = 143,
        rankingRenewal = 144,
        hudAuctionBuff = 145,
        accountAttendance = 146,
        expeditionRecruit = 147,
        uiAvi = 148,
        shopOnUI = 149,
        itemLookConvertInBag = 150,
        newReportBaduser = 151,
        expeditionSummon = 153,
        heroBonus = 154,
        hairTwoTone = 158,
        hudBattleFieldBuff = 159,
        expeditionRank = 160,
        mateTypeSummon = 161,
        permissionZone = 162,
        lootGacha = 163,
        itemEvolvingReRoll = 164,
        ranking_myworld_only = 166,
        eloRating = 167,
        nationMemberLimit = 168,
        packageDemolish = 170,
        itemGuide = 172,
        restrictFollow = 173,
        socketExtract = 174,
        itemlookExtract = 175,
        useCharacterListPage = 176,
        renameExpeditionByItem = 177,
        expeditionImmigration = 178,
        highAbility = 179,
        eventWebLink = 180,
        blessuthstin = 181,
        vehicleZoneSimulation = 182,
        itemSmelting = 183,
        characterInfoLivingPoint = 192,
        useForceAttack = 193,
        specialtyTradeGoods = 194,
        reportBadWordUser = 195,
        residentweblink = 197
        */
    }
}
