<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <!-- Enable Testing Platform support for xunit -->
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AAEmu.Commons\AAEmu.Commons.csproj" />
    <ProjectReference Include="..\AAEmu.Login\AAEmu.Login.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.Telemetry" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport.Abstractions" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.MySql" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\SQL\aaemu_login.sql" Link="SQL\aaemu_login.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
