namespace AAEmu.Login.Network.Message.Static
{
    public enum LoginResponse
    {
        LoginUnknown = 0,
        BadAccount = 1,
        BadResponse = 2,
        DuplicateLogin = 3,
        ServiceTime = 4,
        TryTradeCashTemporal = 5,
        TryTradeCashForever = 6,
        TradedCashTemporal = 7,
        TradedCashForever = 8,
        TryTradeItemServers = 9,
        TradedItemServers = 10,
        TradedAccount = 11,
        TryCheatTemporal = 12,
        TryCheatForever = 13,
        Cheated = 14,
        GambleTemporal = 15,
        GambleForever = 16,
        AbuseBugForever = 17,
        AbuseBugTemporal = 18,
        UseBotForever = 19,
        UseBotTemporal = 20,
        UseBadSoftwareTemporal = 21,
        UseBadSoftwareForever = 22,
        BadUserWorkplace = 23,
        BadUserProxyIP = 24,
        StealInfo = 25,
        FoulLangTemporal = 26,
        FoulLangForever = 27,
        BadGameName = 28,
        DisturbPlay = 29,
        AbnormalPlay = 30,
        DisturbGM = 31,
        FraudfulReport = 32,
        FakeGm = 33,
        WaitCert = 34,
        StealAccountTemporal = 35,
        StealAccountForever = 36,
        FraudfulStealReport = 37,
        StealPerson = 38,
        RequestBySelf = 39,
        RequestByParent = 40,
        Ads = 41,
        RequestByAuthority = 42,
        DefraudPay = 43,
        UnpaidAccount = 44,
        BulkBlockedAccount = 45,
        UnpaidPcbang = 46,
        CongestedServer = 47,
        InvalidMac = 48
    }
}
