<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>CA1861</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AAEmu.Commons\AAEmu.Commons.csproj" />
    <ProjectReference Include="..\AAEmu.Game\AAEmu.Game.csproj" />
    <ProjectReference Include="..\AAEmu.Login\AAEmu.Login.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
