CREATE TABLE `auction_house` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `duration` tinyint(3) NOT NULL,
  `item_id` int(11) NOT NULL,
  `object_id` int(11) NOT NULL,
  `tgrade` tinyint(1) NOT NULL,
  `flags` tinyint(1) NOT NULL,
  `stack_size` int(11) NOT NULL,
  `detail_type` tinyint(1) NOT NULL,
  `creation_time` datetime DEFAULT NULL,
  `lifespan_mins` int(11) NOT NULL,
  `type_1` int(11) NOT NULL,
  `world_id` tinyint(2) NOT NULL,
  `unsecure_date_time` varchar(45) DEFAULT NULL,
  `unpack_date_time` varchar(45) DEFAULT NULL,
  `world_id_2` tinyint(2) NOT NULL,
  `type_2` int(11) NOT NULL,
  `client_name` varchar(45) NOT NULL,
  `start_money` int(11) NOT NULL,
  `direct_money` int(11) NOT NULL,
  `asked` int(11) NOT NULL,
  `bid_world_id` tinyint(1) DEFAULT NULL,
  `type_3` int(11) DEFAULT NULL,
  `bidder_name` varchar(45) DEFAULT NULL,
  `bid_money` int(11) DEFAULT NULL,
  `extra` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
