namespace AAEmu.Game.Core.Packets.G2C;

public static class SCOffsets
{
    // All opcodes here are updated for version 3.5.3.0 r350000 AAClassic
    public const ushort X2EnterWorldResponsePacket = 0x000;
    // первые пакеты, которые необходимы для работы лобби
    public const ushort SCHackGuardRetAddrsRequestPacket = 0x1A0; //+
    public const ushort SCAccountInfoPacket = 0x1F9; //+
    public const ushort SCTrionConfigPacket = 0x08A; //+
    public const ushort SCAccountAttributeConfigPacket = 0x070; //+
    public const ushort SCLevelRestrictionConfigPacket = 0x263; //+
    public const ushort SCTaxItemConfigPacket = 0x0B8; //+
    public const ushort SCInGameShopConfigPacket = 0x14F; //+
    public const ushort SCGameRuleConfigPacket = 0x279; //+
    public const ushort SCProtectFactionPacket = 0x288; //+
    public const ushort SCTaxItemConfig2Packet = 0x229; //+
    public const ushort SCChatSpamDelayPacket = 0x2D6; //+ SCChatSpamConfigPacket
    public const ushort SCInitialConfigPacket = 0x03D; //+

    public const ushort SCGameGuardPacket = 0xfff;    // level = 5

    // остальные пакеты
    //public const ushort SCEnterWorldResponsePacket = 0x000;
    public const ushort SCReconnectAuthPacket = 0x13A;
    public const ushort SCPrepareLeaveWorldPacket = 0x092;
    public const ushort SCLeaveWorldGrantedPacket = 0x1F7;
    public const ushort SCLeaveWorldCanceledPacket = 0x20D;
    public const ushort SCWorldQueuePacket = 0x1D3;
    public const ushort off_39D143F0 = 0x223;
    //public const ushort SCInitialConfigPacket = 0x03D;
    //public const ushort SCTrionConfigPacket = 0x08A;
    public const ushort SCSystemFactionListPacket = 0x296; // was SCFactionListPacket
    public const ushort SCExpeditionListPacket = 0x212;
    public const ushort SCNationMemberListPacket = 0x246;
    public const ushort SCExpeditionRolePolicyListPacket = 0x1AA;
    public const ushort SCExpeditionRolePolicyChangedPacket = 0x123;
    public const ushort SCExpeditionMemberRoleChangedPacket = 0x177;
    public const ushort SCExpeditionOwnerChangedPacket = 0x15F;
    public const ushort SCExpeditionShowRenameUIPacket = 0x044; // SCExpeditionShowRenameUiPacket
    public const ushort SCNationShowRenameUiPacket = 0x28C;
    public const ushort SCFactionRenamedPacket = 0x2BF;
    public const ushort SCFactionRetryRenamePacket = 0x221;
    public const ushort SCFactionRenameFailedPacket = 0x27E;
    public const ushort SCExpeditionCreatedPacket = 0x1AB;
    public const ushort SCExpeditionSponsorChangedPacket = 0x101;
    public const ushort SCExpeditionDismissedPacket = 0x15E;
    public const ushort SCExpeditionWarStatePacket = 0x1DA;
    public const ushort SCExpeditionWarDeclarationMoneyPacket = 0x04B;
    public const ushort SCExpeditionWarKillScorePacket = 0x0CE;
    public const ushort SCExpeditionWarHistoriesPacket = 0x03B;
    public const ushort SCExpdWarHistoriesPacket = 0x02A;
    public const ushort SCExpeditionWarResultPacket = 0x0E2;
    public const ushort SCExpeditionRejoinFailPacket = 0x0BE;
    public const ushort SCDeclarationFailureReasonPacket = 0x116;
    public const ushort SCSetExpeditionProtectDatePacket = 0x068;
    public const ushort SCFactionFriendshipChangedPacket = 0x143;
    public const ushort SCExpeditionInvitationPacket = 0x20B;
    public const ushort SCUnitFactionChangedPacket = 0x1AD;
    public const ushort SCUnitExpeditionChangedPacket = 0x21B;
    public const ushort SCExpeditionMemberListPacket = 0x141;
    public const ushort SCExpeditionMemberListEndPacket = 0x2BD;
    public const ushort SCExpeditionMemberStatusChangedPacket = 0x250;
    public const ushort SCFactionOwnerChangedPacket = 0x213;
    public const ushort SCExpeditionImmigrationListPacket = 0x125;
    public const ushort SCExpeditionDescReceivedPacket = 0x260;
    public const ushort SCExpeditionExpAddReceivedPacket = 0x146;
    public const ushort SCNationMemberCountListPacket = 0x230;
    public const ushort SCNationRelationVotePacket = 0x0DD;
    public const ushort SCNationInfoSetPacket = 0x1A1;
    public const ushort SCNationInfoGetPacket = 0x257;
    public const ushort SCNationRelationSetGmPacket = 0x197;
    public const ushort SCNationMemberAddPacket = 0x1CA;
    public const ushort SCNationMemberRemovePacket = 0x0E7;
    public const ushort SCNationMemberStateChangePacket = 0x022;
    public const ushort SCExpeditionImmgrationPacket = 0x199;
    public const ushort SCExpeditionImmgrationRequestPacket = 0x27D;
    public const ushort SCExpeditionImmgrationCancelPacket = 0x14A;
    public const ushort SCFamilyInvitationPacket = 0x052;
    public const ushort SCFamilyRemovedPacket = 0x1E7;
    public const ushort SCFamilyMemberRemovedPacket = 0x2C6;
    public const ushort SCFamilyOwnerChangedPacket = 0x1E5;
    public const ushort SCFamilyTitleChangedPacket = 0x0C3;
    public const ushort SCFamilyMemberNameChangedPacket = 0x0EE;
    public const ushort SCFamilyTitlePacket = 0x291;
    public const ushort SCFamilyMemberOnlinePacket = 0x10A;
    public const ushort SCFamilyMemberRoleChangePacket = 0x09C;
    public const ushort SCFamilyMemberLevelChangePacket = 0x0D6;
    public const ushort SCFamilyInfoSetPacket = 0x056;
    public const ushort SCFamilyExpChangeNotifyPacket = 0x091;
    public const ushort SCFamilyNameChangeNotifyPacket = 0x129;
    public const ushort SCCharacterDeleteResponsePacket = 0x2A2;
    public const ushort SCCharacterDeletedPacket = 0x2A7;
    public const ushort SCCharacterDeleteCanceledPacket = 0x183;
    public const ushort SCCharacterCreationFailedPacket = 0x256;
    public const ushort SCRaceCongestionPacket = 0x05C;
    public const ushort SCCheckRaceCongestionResponsePacket = 0x2A4;
    public const ushort SCCharacterInvenInitPacket = 0x063;
    public const ushort SCCharacterInvenContentsPacket = 0x1C7;
    public const ushort SCCharacterInvenExpandedPacket = 0x051;
    public const ushort SCNotifyResurrectionPacket = 0x138;
    public const ushort SCCharacterResurrectedPacket = 0x07A;
    public const ushort SCForceAttackSetPacket = 0x0E6;
    public const ushort SCBmPointPacket = 0x055;
    public const ushort SCAddActionPointPacket = 0x217;
    public const ushort SCCharacterLpManagedPacket = 0x1E8;
    public const ushort SCExpertLimitModifiedPacket = 0x13C;
    public const ushort SCExpertExpandedPacket = 0x06A;
    //public const ushort SCAccountInfoPacket = 0x1F9;
    public const ushort SCResponseCombatUnitsPacket = 0x158;
    public const ushort SCUccCheckedPacket = 0x009;
    public const ushort SCSlaveCreatedPacket = 0x083;
    public const ushort SCSlaveRemovedPacket = 0x255;
    public const ushort SCSlaveDespawnPacket = 0x1B6;
    public const ushort SCSlaveBoundPacket = 0x021;
    public const ushort SCMySlavePacket = 0x26E;
    public const ushort SCEscapeSlavePacket = 0x124;
    public const ushort SCSlaveEquipmentExpiredPacket = 0x25C;
    public const ushort SCSlaveEquipmentFlagsChangedPacket = 0x2D3;
    public const ushort SCUnitsRemovedPacket = 0x2CF;
    public const ushort SCSetUnitOfflinePacket = 0x07E;
    public const ushort SCFollowAskPacket = 0x25A;
    public const ushort SCFollowRespPacket = 0x15A;
    public const ushort SCSkillControllerStatePacket = 0x21C;
    public const ushort SCActiveWeaponChangedPacket = 0x1CF;
    public const ushort SCUnitNameChangedPacket = 0x06B;
    public const ushort SCUnitDeathPacket = 0x053;
    public const ushort SCUnitTeleportPacket = 0x157;
    public const ushort SCBlinkUnitPacket = 0x155; // SCUnitBlinkPacket
    public const ushort SCUnitAttachedPacket = 0x29E;
    public const ushort SCUnitDetachedPacket = 0x2AA;
    public const ushort SCUnitInvisiblePacket = 0x050;
    public const ushort SCUnitFlyingStateChangedPacket = 0x017;
    public const ushort SCTargetChangedPacket = 0x261;
    public const ushort SCUnitEquipmentsRndAttrUnitModifierAvtivateChangedPacket = 0x2D4;
    public const ushort SCUnitEquipmentIdsPacket = 0x1C5;
    public const ushort SCSplitCofferItemResultPacket = 0x198;
    public const ushort SCSyncItemLifespanPacket = 0x2D5;
    public const ushort SCSpecialtyRatioPacket = 0x06E; // off_39D1490C
    public const ushort SCSpecialtyGoodsPacket = 0x006; // off_39D14918
    public const ushort SCSpecialtyRecordsPacket = 0x271;
    public const ushort off_39D14930 = 0x281;
    public const ushort SCSocketingResultPacket = 0x09E;
    public const ushort SCEnchantMagicalResultPacket = 0x121;
    public const ushort SCRefurbishmentResultPacket = 0x1F1;
    public const ushort SCItemSmeltingResultPacket = 0x08F;
    public const ushort SCSocketingResult2Packet = 0x131;
    public const ushort SCSkillStartedPacket = 0x1DB; // off_39D14978
    public const ushort SCSkillFiredPacket = 0x11B; // off_39D14984
    public const ushort SCSkillEndedPacket = 0x1BC;
    public const ushort SCSkillStoppedPacket = 0x2AB;
    public const ushort SCCastingStoppedPacket = 0x2AE;
    public const ushort SCCastingDelayedPacket = 0x1F6;
    public const ushort SCUnitDamagedPacket = 0x0E9; // off_39D149C0
    public const ushort SCUnitHealedPacket = 0x235; // off_39D149CC
    public const ushort SCBuffStatePacket = 0x04E; // off_39D149D8
    public const ushort SCBuffCreatedPacket = 0x1EE; // off_39D149E4
    public const ushort SCBuffRemovedPacket = 0x175; // off_39D149F0
    public const ushort SCGlideBuffRemovedPacket = 0x17F; // off_39D149FC
    public const ushort SCBuffUpdatedPacket = 0x12B; // off_39D14A08
    public const ushort SCUnitPointsPacket = 0x12E;
    public const ushort SCCombatEngagedPacket = 0x254;
    public const ushort SCCombatClearedPacket = 0x180;
    public const ushort SCCombatFirstHitPacket = 0x0CD;
    public const ushort SCDumpCombatStatPacket = 0x2CB;
    public const ushort SCDuelChallengedPacket = 0x0BD;
    public const ushort SCDuelStartCountdownPacket = 0x184;
    public const ushort SCDuelStartedPacket = 0x100;
    public const ushort SCDuelEndedPacket = 0x22A;
    public const ushort SCDuelStatePacket = 0x193;
    public const ushort SCHouseBuildProgressPacket = 0x238;
    public const ushort SCHousePermissionChangedPacket = 0x156;
    public const ushort SCHouseDemolishedPacket = 0x2A0;
    public const ushort SCHouseRemovedPacket = 0x160;
    public const ushort SCHouseFarmPacket = 0x03A;
    public const ushort SCToggleHousingRecoverPacket = 0x090;
    public const ushort SCHouseResetForSalePacket = 0x0F7;
    public const ushort SCHouseSoldPacket = 0x1E4;
    public const ushort SCHouseOwnerNameChangedPacket = 0x1E1;
    public const ushort SCHouseRotatedPacket = 0x15B;
    public const ushort SCHousingDecoLimitExpandedPacket = 0x0A4;
    public const ushort SCJoinedChatChannelPacket = 0x222;
    public const ushort SCLeavedChatChannelPacket = 0x19C;
    public const ushort SCChatMessagePacket = 0x07C;
    public const ushort SCChatTokenPacket = 0x096;
    public const ushort SCNpcChatMessagePacket = 0x284;
    public const ushort SCReportedSpammerPacket = 0x098;
    public const ushort SCNoticeMessagePacket = 0x1A3;
    public const ushort SCChatFailedPacket = 0x2B2;
    public const ushort SCAskToJoinTeamPacket = 0x057;
    public const ushort SCAskToJoinTeamAreaPacket = 0x18D;
    public const ushort SCRejectedTeamPacket = 0x0F1;
    public const ushort SCLeavedTeamPacket = 0x103;
    public const ushort SCTeamDismissedPacket = 0x245;
    public const ushort SCTeamMemberJoinedPacket = 0x001;
    public const ushort SCTeamMemberLeavedPacket = 0x013;
    public const ushort SCTeamOwnerChangedPacket = 0x234;
    public const ushort SCTeamMemberRoleChangePacket = 0x173;
    public const ushort SCTeamBecameRaidteamPacket = 0x2D9;
    public const ushort SCTeamMemberMovedPacket = 0x0F4;
    public const ushort SCRefreshTeamMemberPacket = 0x152;
    public const ushort SCTeamRemoteMembersExPacket = 0xfff;
    public const ushort SCTeamAreaInvitedPacket = 0x176;
    public const ushort SCOverHeadMarkerSetPacket = 0x1C2;
    public const ushort SCTeamPingPosPacket = 0x237;
    public const ushort SCTeamAckRiskyActionPacket = 0x04A;
    public const ushort SCTeamAskHandOverOwnerPacket = 0x2AC;
    public const ushort SCTeamAskAcceptOwnerOfferPacket = 0x047;
    public const ushort SCTeamHandOverOwnerOfferResultPacket = 0x115;
    public const ushort SCSiegeReinforcePacket = 0x026;
    public const ushort SCSiegeMemberPacket = 0x22F;
    public const ushort SCSiegeAlertPacket = 0x26B;
    public const ushort SCConflictZoneStatePacket = 0x283;
    public const ushort SCConflictZoneHonorPointSumPacket = 0x14D;
    public const ushort SCFestivalZoneStatePacket = 0x040;
    public const ushort SCTimeOfDayPacket = 0x008;
    public const ushort SCDetailedTimeOfDayPacket = 0x2C0;
    public const ushort SCNpcInteractionSkillListPacket = 0x10F;
    public const ushort SCNpcInteractionEndedByZonePacket = 0x059;
    public const ushort SCWorldInteractionSkillListPacket = 0x1A8;
    public const ushort SCCancelWorldInteractionPacket = 0x08E;
    public const ushort SCNpcInteractionStatusChangePacket = 0x049;
    public const ushort SCVegetationCutdowningPacket = 0x28D;
    public const ushort SCNpcFriendshipListPacket = 0x187;
    public const ushort SCNpcFriendshipChangedPacket = 0x19F;
    public const ushort SCCompletedQuestsPacket = 0x01F;
    public const ushort SCCraftItemNulockPacket = 0x242;
    public const ushort SCLootableStatePacket = 0x11A;
    public const ushort SCUnitLootingStatePacket = 0x1B9;
    public const ushort SCLootItemTookPacket = 0x2C9;
    public const ushort SCLootItemFailedPacket = 0x244;
    public const ushort SCLootDiceSummaryPacket = 0x29F;
    public const ushort SCExpChangedPacket = 0x0D1;
    public const ushort SCAbilityExpChangedPacket = 0x0AD;
    public const ushort SCRecoverableExpPacket = 0x13E;
    public const ushort SCMileageChangedPacket = 0x1CE;
    public const ushort SCLevelChangedPacket = 0x240;
    public const ushort SCBalanceLevelChangedPacket = 0x25B;
    public const ushort SCUnitModelPostureChangedPacket = 0x0B1;
    public const ushort SCSkillLearnedPacket = 0x262;
    public const ushort SCBuffLearnedPacket = 0xfff;
    public const ushort SCDoodadCompleteQuestPacket = 0x19B;
    public const ushort SCSkillsResetPacket = 0x0F3;
    public const ushort SCAbilitySwappedPacket = 0x0AF;
    public const ushort SCSpecialAbilityActivedPacket = 0x179;
    public const ushort SCAbilitySetUpdatedPacket = 0x106;
    public const ushort SCAbilitySetUsableSlotCountUpdatedPacket = 0x13B;
    public const ushort SCErrorMsgPacket = 0x0FE;
    public const ushort SCDoodadRemovedPacket = 0x178;
    public const ushort SCDoodadChangedPacket = 0x03C;
    public const ushort SCDoodadPhaseChangedPacket = 0x061; // off_39D14E40
    public const ushort SCDoodadPuzzleScenePacket = 0x2C3;
    public const ushort SCDoodadSoundPacket = 0x268;
    public const ushort SCDoodadsRemovedPacket = 0x0EB;
    public const ushort SCDoodadOriginatorPacket = 0x2B0;
    public const ushort SCDoodadInteractionCallbackPacket = 0x1F2;
    public const ushort SCMineAmountPacket = 0x0D2; // off_39D14E88
    public const ushort SCMailFailedPacket = 0x0E5; // SCMailFailPacket
    public const ushort SCCountUnreadMailPacket = 0x26F;
    public const ushort SCMailSentPacket = 0x066;
    public const ushort SCMailListPacket = 0x20A;
    public const ushort SCMailListEndPacket = 0x060;
    public const ushort SCMailReceiverOpenedPacket = 0x2A6;
    public const ushort SCMailAttachmentTakenPacket = 0x015;
    public const ushort SCMailDeletedPacket = 0x1EA;
    public const ushort SCSpamReportedPacket = 0x0CC;
    public const ushort SCMailReturnedPacket = 0x0D4;
    public const ushort SCMailStatusUpdatedPacket = 0x00C;
    public const ushort SCMailRemovedPacket = 0x0D7;
    public const ushort SCMateSpawnedPacket = 0x0CF;
    public const ushort SCMateEquipmentExpiredPacket = 0x251;
    public const ushort SCEmotionExpressedPacket = 0x095;
    public const ushort SCActionSlotsPacket = 0x0D8;
    public const ushort SCAuctionBidPacket = 0x264;
    public const ushort SCAuctionSoldRecordPacket = 0x075;
    public const ushort SCUnitTrackedPacket = 0x10E;
    public const ushort SCBombUpdatedPacket = 0x23C;
    public const ushort SCCombatTextPacket = 0x042;
    public const ushort SCSkillCooldownResetPacket = 0x0DE;
    public const ushort SCPlotEndedPacket = 0x2B7;
    public const ushort SCPlotProcessingTimePacket = 0x169;
    public const ushort SCPlotCastingStoppedPacket = 0x133;
    public const ushort SCPlotChannelingStoppedPacket = 0x0A2;
    public const ushort SCEnvDamagePacket = 0x0FB;
    public const ushort SCSnowingEverywherePacket = 0x032; // was SCSnowOnOffPacket
    public const ushort SCDiceValuePacket = 0x243;
    public const ushort SCDiceBidRuleChangePacket = 0x01C;
    public const ushort SCHungPacket = 0x1A2;
    public const ushort SCUnhungPacket = 0x14B;
    public const ushort SCAttachToDoodadPacket = 0x088; // SCBondDoodadPacket
    public const ushort SCDetachFromDoodadPacket = 0x27A; // SCUnbondDoodadPacket
    public const ushort SCPlaySequencePacket = 0x097;
    public const ushort SCGimmicksRemovedPacket = 0x202;
    public const ushort SCGimmickJointsBrokenPacket = 0x294;
    public const ushort SCGimmickResetJointsPacket = 0x227;
    public const ushort SCGimmickGraspedPacket = 0x265;
    public const ushort SCWorldRaycastingResultPacket = 0x24E;
    public const ushort SCUnitCollisionResultDebugPacket = 0x0EC;
    public const ushort SCWorldAimpointPacket = 0x174;
    public const ushort SCQuestContextFailedPacket = 0x0F0;
    public const ushort off_39D15098 = 0x1D0;
    public const ushort SCQuestContextAcceptConditionalPacket = 0x139;
    public const ushort SCQuestContextCompletedPacket = 0x14C;
    public const ushort SCQuestContextResetPacket = 0x1B7;
    public const ushort SCDoodadPhaseMsgPacket = 0x11C;
    public const ushort SCQuestRewardedByMailPacket = 0x01B;
    public const ushort SCQuestListPacket = 0x27C;
    public const ushort SCQuestMailSentPacket = 0x012;
    public const ushort SCScheduleItemSentPacket = 0x105;
    public const ushort SCGmCommandPacket = 0x154;
    public const ushort SCGmDumpInventoryPacket = 0x149;
    public const ushort SCGmDumpCompletedQuestsPacket = 0x2B6;
    public const ushort SCGmDumpGradeEnchantRatioPacket = 0x2A3;
    public const ushort SCGmDumpCharPacket = 0x2A1;
    public const ushort SCGmDumpAppellationPacket = 0x18F;
    public const ushort SCGmDumpAchievementPacket = 0x1EC;
    public const ushort SCGmDumpGamePointPacket = 0x00F;
    public const ushort SCGmDumpPstatPacket = 0x29A;
    public const ushort SCGmDumpRecordPacket = 0x26C;
    public const ushort SCGmDumpRestirctPacket = 0x147;
    public const ushort SCGmDumpSkillPacket = 0x1B1;
    public const ushort off_39D15194 = 0x2B1;
    public const ushort SCGmDumpReturnDistrictPacket = 0x1D2;
    public const ushort SCGmDumpDailyResetPacket = 0x0AE;
    public const ushort SCGmDumpExploredRegionPacket = 0xfff;
    public const ushort SCGmDumpGuidPacket = 0x16A;
    public const ushort SCGmDumpBuycodePacket = 0x292;
    public const ushort off_39D151DC = 0x06F;
    public const ushort SCKickedPacket = 0x0E3;
    public const ushort SCAccountWarnedPacket = 0x1FD;
    public const ushort SCAccountWarnedCodePacket = 0x062;
    public const ushort SCAboxTeleportPacket = 0x09A;
    public const ushort SCPortalDeletedPacket = 0x0B5;
    public const ushort SCUnitPortalUsedPacket = 0x12A;
    public const ushort SCIncreasedFavoritePortalLimitPacket = 0x205;
    public const ushort SCSoundAreaEventPacket = 0x0C1;
    public const ushort SCAreaChatBubblePacket = 0x1E3;
    public const ushort SCChatBubblePacket = 0x19E;
    public const ushort SCAreaTeamMsgPacket = 0x132;
    public const ushort SCAppellationChangedPacket = 0x172;
    public const ushort off_39D15278 = 0x073;
    public const ushort SCNuonsArrowMsgPacket = 0x118;
    public const ushort SCCooldownsPacket = 0x1DF;
    public const ushort SCDoodadUccDataPacket = 0x18C;
    public const ushort SCUccNameLoadedPacket = 0x18E;
    public const ushort SCNaviTeleportPacket = 0x1BD;
    public const ushort SCTradeStartedPacket = 0x030;
    public const ushort SCCanStartTradePacket = 0x165;
    public const ushort SCCannotStartTradePacket = 0x01D; // SCCanNotStartTradePacket
    public const ushort SCTradeCanceledPacket = 0x0FA;
    public const ushort SCTradeItemPutupPacket = 0x05F;
    public const ushort SCTradeItemTookdownPacket = 0x0A6;
    public const ushort SCOtherTradeOkPacket = 0x13D;
    public const ushort SCTradeLockUpdatePacket = 0x2CD;
    public const ushort SCTowerDefListPacket = 0x06C;
    public const ushort SCTowerDefStartPacket = 0x04C;
    public const ushort SCTowerDefEndPacket = 0x16F;
    public const ushort SCTowerDefWaveStartPacket = 0x07D;
    public const ushort SCCrimeReportedPacket = 0x002;
    public const ushort SCCriminalArrestedPacket = 0x112;
    public const ushort SCAskImprisonOrTrialPacket = 0x273;
    public const ushort SCInviteJuryPacket = 0x272;
    public const ushort SCSummonJuryPacket = 0x126;
    public const ushort SCJuryBeSeatedPacket = 0x028;
    public const ushort SCSummonDefendantPacket = 0x025;
    public const ushort SCCrimeDataPacket = 0x004;
    public const ushort SCCrimeRecordsPacket = 0x0A9;
    public const ushort SCTrialInfoPacket = 0x206;
    public const ushort SCChangeTrialStatePacket = 0x018;
    public const ushort SCChangeJuryOkCountPacket = 0x153;
    public const ushort SCChangeJurySentenceCountPacket = 0x231;
    public const ushort SCTrialWaitStatusPacket = 0x135;
    public const ushort SCJuryWaitStatusPacket = 0x2BB;
    public const ushort SCRulingStatusPacket = 0x275;
    public const ushort SCRulingClosedPacket = 0x0E4;
    public const ushort SCAudienceJoinedPacket = 0x1CC;
    public const ushort SCAudienceLeftPacket = 0x137;
    public const ushort SCJuryWaitingNumberPacket = 0x02E;
    public const ushort SCTrialCanceledPacket = 0x06D;
    public const ushort SCBotSuspectReportedPacket = 0x17C;
    public const ushort SCBotSuspectArrestedPacket = 0x04F;
    public const ushort SCSuspectGoingBotTrialPacket = 0x00E;
    public const ushort SCUnderWaterPacket = 0x064;
    public const ushort SCCharacterGamePointsPacket = 0x1BA;
    public const ushort SCGamePointInitedPacket = 0x200;
    public const ushort SCJuryPointChangedPacket = 0x2C1;
    public const ushort SCAppliedToInstantGamePacket = 0x185;
    public const ushort SCCancelInstantGamePacket = 0x0B0;
    public const ushort SCInviteToInstantGamePacket = 0x00B;
    public const ushort SCInstantGameJoinedPacket = 0x295;
    public const ushort SCInstantGameReadyPacket = 0x1F3;
    public const ushort SCInstantGameStartPacket = 0x094;
    public const ushort SCInstantGameUpdateTimePacket = 0x196;
    public const ushort SCInstantGameEndPacket = 0x151;
    public const ushort SCInstantGameRoundResultPacket = 0x0AC;
    public const ushort SCInstantGameScorePacket = 0x190;
    public const ushort SCInstantGameShipStatusPacket = 0x058;
    public const ushort SCInstantGameKillPacket = 0x2AD;
    public const ushort SCInstantGameKillstreakPacket = 0x23E;
    public const ushort SCInstantGameKillstreakResetPacket = 0x11F;
    public const ushort SCInstantGameUnearnedWinPacket = 0x171;
    public const ushort SCInstantGamePickShipCountPacket = 0x2B8;
    public const ushort SCProcessingInstancePacket = 0x162;
    public const ushort SCInstanceVisitCountsPacket = 0x007;
    public const ushort SCDailyResetPacket = 0x0F9;
    public const ushort SCInstanceVisitCountChangePacket = 0x1FB;
    public const ushort SCDelayedTaskOnInGameNotifyPacket = 0x01A;
    public const ushort SCAppellationsPacket = 0x2C5;
    public const ushort SCAppellationGainedPacket = 0x145;
    public const ushort off_39D155B4 = 0x0A0;
    public const ushort SCTutorialSavedPacket = 0x0B3;
    public const ushort SCEmblemUploadedPacket = 0x082;
    public const ushort SCEmblemDownloadedPacket = 0x0FD;
    public const ushort SCDoodadUccStringPacket = 0x0A5;
    public const ushort SCSlaveStatusPacket = 0x188;
    public const ushort SCMateStatusPacket = 0x10B;
    public const ushort SCFriendsPacket = 0x0E8;
    public const ushort SCSearchListPacket = 0x253;
    public const ushort SCAddFriendPacket = 0x11E;
    public const ushort SCDeleteFriendPacket = 0x041;
    public const ushort SCFriendStatusChangedPacket = 0x189;
    public const ushort SCBlockedUsersPacket = 0x21D;
    public const ushort SCAddBlockedUserPacket = 0x27F;
    public const ushort SCDeleteBlockedUserPacket = 0x031;
    public const ushort SCCharacterBriefPacket = 0x168;
    public const ushort SCShowPlaytimePacket = 0x1D4;
    public const ushort SCCharacterRenamedPacket = 0x1A9;
    public const ushort SCUpdateBotCheckInfoPacket = 0x1B0;
    public const ushort SCItemUccChangedPacket = 0x12C;
    public const ushort SCShowQuestAreaPacket = 0x01E;
    public const ushort SCShowCommonFarmShapePacket = 0x241;
    public const ushort SCTelescopeToggledPacket = 0x0CB;
    public const ushort SCTransferTelescopeToggledPacket = 0x087;
    public const ushort SCBossTelescopeToggledPacket = 0x089;
    public const ushort SCSchoolOfFishFinderToggledPacket = 0x269;
    public const ushort SCDominionDeletedPacket = 0x299;
    public const ushort SCDominionOwnerChangedPacket = 0x12F;
    public const ushort SCDominionTaxratePacket = 0x1E9;
    public const ushort SCNationalTaxratePacket = 0x220;
    public const ushort SCNationalMonumentChangedPacket = 0x107;
    public const ushort SCDominionTaxChangedPacket = 0x079;
    public const ushort SCDominionNonPvpStartedPacket = 0x09B;
    public const ushort SCDominionNonPvpStoppedPacket = 0x2C4;
    public const ushort SCResidentMapPacket = 0x1C6;
    public const ushort SCResidentInfoPacket = 0x225;
    public const ushort SCResidentBalanceInfoPacket = 0x239;
    public const ushort SCResidentInfoListPacket = 0x0C9;
    public const ushort SCResidentMemberInfoPacket = 0x29B;
    public const ushort SCFactionIndependencePacket = 0x22C;
    public const ushort SCFactionImmigrateInvitePacket = 0x1C9;
    public const ushort SCFactionImmigrateInviteResultPacket = 0x00A;
    public const ushort SCFactionImmigrateToOriginResultPacket = 0x24C;
    public const ushort SCFactionKickToOriginResultPacket = 0x119;
    public const ushort SCFactionDeclareHostileResultPacket = 0x150;
    public const ushort SCFactionRelationExpiredPacket = 0x28A;
    public const ushort SCFactionMobilizationOrderPacket = 0x1F5;
    public const ushort SCFactionMobilizationOrderSuccessPacket = 0x04D;
    public const ushort SCExpeditionRecruitmentsGetPacket = 0x120;
    public const ushort SCExpeditionRecruitmentAddPacket = 0x195;
    public const ushort SCExpeditionRecruitmentDeletePacket = 0x21E;
    public const ushort SCExpeditionApplicantsGetPacket = 0x0B9;
    public const ushort SCExpeditionApplicantAddPacket = 0x0AB;
    public const ushort SCExpeditionApplicantDeletePacket = 0x186;
    public const ushort SCExpeditionApplicantAcceptPacket = 0x1D8;
    public const ushort SCExpeditionApplicantRejectPacket = 0x0D5;
    public const ushort SCExpeditionApplicantResultPacket = 0x046;
    public const ushort SCExpeditionSummonGetPacket = 0x0BA;
    public const ushort SCExpeditionSummonPacket = 0x1C1;
    public const ushort SCShowDemoModeUiPacket = 0x19A;
    public const ushort SCResetDemoCharItemsPacket = 0x081;
    public const ushort SCResetDemoCharPacket = 0x16D;
    public const ushort SCResetDemoCharActionsPacket = 0x2A9;
    public const ushort SCSetBreathPacket = 0x20F;
    public const ushort SCAggroTargetChangedPacket = 0x1D9;
    //public const ushort SCHackGuardRetAddrsRequestPacket = 0x1A0; // SCHgReqPacket
    public const ushort SCSetGgArgsPacket = 0x05E;
    public const ushort off_39D1592C = 0x005;
    public const ushort SCReqBattleFieldPacket = 0x02F;
    public const ushort SCCraftFailedPacket = 0x22D;
    public const ushort SCUnitLocationPacket = 0x086;
    public const ushort SCRestrictInfoPacket = 0x0EA;
    public const ushort SCIsUnitInFarmPacket = 0x05B;
    public const ushort SCResponseUIDataPacket = 0x258; // SCResponseUiDataPacket
    public const ushort SCUnitVisualOptionsPacket = 0x1DE;
    public const ushort SCUnitOpenEquipInfoPacket = 0x144;
    public const ushort SCNotifyUiMessagePacket = 0x214;
    public const ushort off_39D159A4 = 0x003;
    public const ushort SCRefreshInCharacterListPacket = 0x15D;
    public const ushort SCICSMenuListPacket = 0x285; // SCIcsMenuListPacket
    public const ushort SCICSGoodListPacket = 0x274; // SCIcsGoodsListPacket
    public const ushort SCICSGoodDetailPacket = 0x0FF; // SCIcsGoodsDetailPacket
    public const ushort SCICSCheckTimePacket = 0x0E0; // SCIcsCheckTimePacket
    public const ushort SCICSBuyResultPacket = 0x093; // SCIcsBuyResultPacket
    public const ushort SCICSSyncGoodPacket = 0x22E; // SCIcsSyncGoodsPacket
    public const ushort SCICSCashPointPacket = 0x209; // SCIcsCashPointPacket
    public const ushort SCBountyListPacket = 0x067;
    public const ushort SCInviteCanceledPacket = 0x2AF;
    public const ushort SCPlaySoundPacket = 0x1A7;
    public const ushort SCSendUserMusicPacket = 0x020;
    public const ushort SCUserNotesLoadedPacket = 0x28B;
    public const ushort SCPauseUserMusicPacket = 0x0F8;
    public const ushort SCEnsembleSuggestedPacket = 0x0B2;
    public const ushort off_39D15A64 = 0x134;
    public const ushort SCGetSlotCountPacket = 0x266;
    public const ushort SCSecondPassSettedPacket = 0x08B;
    public const ushort SCSecondPassKeyTablesPacket = 0x0F2;
    public const ushort SCSecondPassCreatedPacket = 0x1AE;
    public const ushort SCSecondPassChangedPacket = 0x21A;
    public const ushort SCSecondPassCheckedPacket = 0x1D6;
    public const ushort SCSecondPassClearedPacket = 0x2A8;
    public const ushort SCSecondPassCheckOverFailedPacket = 0x0A1;
    public const ushort SCSecondPassAccountLockedPacket = 0x0B4;
    public const ushort SCSecondPassReservedClearTimePacket = 0x11D;
    public const ushort SCScheduleItemUpdatePacket = 0x136;
    public const ushort SCScheduledEventStartedPacket = 0x23D;
    public const ushort SCScheduledEventEndedPacket = 0x111;
    public const ushort SCMouldListPacket = 0x1AC;
    public const ushort SCMouldAskedPacket = 0x019;
    public const ushort SCMouldTanekPacket = 0x182;
    public const ushort SCToggleBeautyShopResponsePacket = 0x02D; // SCToggleBeautyshopResponsePacket
    public const ushort SCSpecialtyCurrentPacket = 0x232;
    public const ushort SCUnitIdleStatusPacket = 0x17B;
    public const ushort SCRaceCondPacket = 0x24B;
    public const ushort SCRacingPacket = 0x0ED;
    public const ushort SCRaceResultPacket = 0x233;
    public const ushort SCRankRewardMailPacket = 0x224;
    public const ushort off_39D15B84 = 0x0D3;
    public const ushort off_39D15B90 = 0x1E0;
    public const ushort off_39D15B9C = 0x104;
    public const ushort SCAchievementsPacket = 0x08C;
    public const ushort SCAchievementChangedPacket = 0x23A;
    public const ushort SCAchievementCompletedPacket = 0x0B6;
    public const ushort SCAchievementResetedPacket = 0x010;
    public const ushort SCAchievementItemSentPacket = 0x282;
    public const ushort SCTodayAssignmentItemSentPacket = 0x00D;
    public const ushort SCTodayAssignmentChangedPacket = 0x1A5;
    public const ushort off_39D15BFC = 0x1D5;
    public const ushort off_39D15C08 = 0x0DA;
    public const ushort SCUpdatePremiumPointPacket = 0x278;
    public const ushort SCPremiumPointChangedPacket = 0x17A;
    public const ushort SCUnitGmModeChangedPacket = 0x117;
    public const ushort SCUnitPvPPointsChangedPacket = 0x19D; // SCUnitPvpPointsChangedPacket
    public const ushort SCRankAlarmPacket = 0x0F6;
    public const ushort SCICSExchangeRatioPacket = 0x293; // SCIcsExchangeRatioPacket
    public const ushort SCPremiumServiceListPacket = 0x1FA;
    public const ushort SCPremiumServiceBuyCountPacket = 0x074;
    public const ushort SCSysIndunStatPacket = 0x170;
    public const ushort SCSysIndunIndexPacket = 0x023;
    public const ushort SCProtectSensitiveOperationPacket = 0x17D;
    public const ushort SCSensitiveOperationVerifyUrlPacket = 0x1BE;
    public const ushort SCSensitiveOperationVerifySuccessPacket = 0x140;
    public const ushort SCAntibotDataPacket = 0x142;
    public const ushort SCAntibotPunishPacket = 0x10D;
    public const ushort SCAddCharacterPStatPacket = 0x201;
    public const ushort SCUnlockCurrencySlotPacket = 0x0C6;
    public const ushort SCMateEquipmentFlagsChangedPacket = 0x0BC;
    public const ushort SCStoreTradeFailedPacket = 0x036;
    public const ushort SCExploredRegionsPacket = 0xfff;
    public const ushort SCExploredRegionUpdatedPacket = 0x1ED;
    public const ushort SCUpdateSlaveSourceItemPacket = 0x03E;
    public const ushort SCRequestQuitPacket = 0x226;
    public const ushort SCWorldMessagePacket = 0x2B5;
    public const ushort SCAccountAttributeRemovedPacket = 0x10C;
    //public const ushort SCAccountAttributeConfigPacket = 0x070;
    public const ushort SCIdleKickPacket = 0x159;
    public const ushort SCIndunDirectTelPacket = 0x23F;
    public const ushort SCWorldRestrictOwnerChangePacket = 0x1B3;
    //public const ushort SCLevelRestrictionConfigPacket = 0x263;
    //public const ushort SCTaxItemConfigPacket = 0x0B8;
    public const ushort SCReputationChangedPacket = 0x1E6;
    public const ushort SCReputationRelationsPacket = 0x248;
    public const ushort SCReputationRelationChangedPacket = 0x18B;
    public const ushort SCHeroSeasonInfoPacket = 0x2C7;
    public const ushort SCHeroSeasonOffPacket = 0x1C8;
    public const ushort SCHeroScoreUpdatedPacket = 0x289;
    public const ushort SCHeroRankingListPacket = 0x014;
    public const ushort SCHeroCandidateListPacket = 0x228;
    public const ushort SCHeroCandidateNotificationPacket = 0x25E;
    public const ushort SCHeroListPacket = 0x078;
    public const ushort SCHeroVotingPacket = 0x011;
    public const ushort SCHeroEventStatePacket = 0x280;
    public const ushort SCHeroElectionMailPacket = 0x033;
    public const ushort SCHeroInfoDeletedPacket = 0x29D;
    public const ushort SCHeroInfoUpdatedPacket = 0x029;
    public const ushort SCHeroMobilizationOrderUpdatedPacket = 0x0A7;
    public const ushort SCRebuildHouseTaxInfoPacket = 0x0D0;
    //public const ushort SCIngameShopConfigPacket = 0x14F;
    //public const ushort SCGameRuleConfigPacket = 0x279;
    //public const ushort SCProtectFactionPacket = 0x288; // 
    //public const ushort SCTaxItemConfig2Packet = 0x229;
    public const ushort off_39D15E84 = 0x1DC;
    public const ushort SCTenprotectStubCall1Packet = 0x045;
    public const ushort SCTenprotectStubCall2Packet = 0x14E;
    public const ushort SCTenprotectStubCall3Packet = 0x24D;
    public const ushort SCTenprotectStubCall4Packet = 0x05A;
    public const ushort SCTenprotectStubCall5Packet = 0x259;
    public const ushort SCRepresentCharacterPacket = 0x192;
    public const ushort off_39D15ED8 = 0x276;
    public const ushort SCAccountAttendancePacket = 0x298;
    public const ushort SCDbAttendanceTimePacket = 0x252;
    public const ushort SCCurServerTimePacket = 0x085;
    public const ushort SCUiTextsKeyPacket = 0x09F;
    public const ushort SCTrialBotReportedPacket = 0x1AF;
    public const ushort off_39D15F20 = 0x215;
    public const ushort off_39D15F2C = 0x1FF;
    public const ushort SCPremiumBonusListPacket = 0x161;
    public const ushort SCRevenueSanctionMsgPacket = 0x1F0;
    public const ushort SCSuccessedReportSpammerPacket = 0x0C4;
    public const ushort SCMailForceOpenPacket = 0x130;
    public const ushort SCSpawnedMonitorNpcsPacket = 0x108;
    public const ushort SCMonitorNpcSpawnedPacket = 0x110;
    public const ushort off_39D15F80 = 0x1B2;
    public const ushort off_39D15F8C = 0x2CA;
    public const ushort off_39D15F98 = 0x249;
    public const ushort SCListSkillActiveTypsPacket = 0x1FC;
    public const ushort SCUpdateSkillActiveTypePacket = 0x034;
    public const ushort SCGachaLootPackItemLogPacket = 0x2C2;
    public const ushort off_39D15FC8 = 0x16B;
    public const ushort off_39D15FD4 = 0x286;
    public const ushort off_39D15FE0 = 0x0A8;
    public const ushort SCSetInstantTimePacket = 0x077;
    public const ushort SCDisarmamentChangedPacket = 0x26A;
    public const ushort SCHighAbilityActivedPacket = 0x21F;
    public const ushort SCHighAbilityExpChangedPacket = 0x270;
    public const ushort SCHighAbilityLevelUpPacket = 0x12D;
    public const ushort SCHighAbilityOrderChangePacket = 0x2B9;
    public const ushort SCBlessUthstinInitStatsPacket = 0x277;
    public const ushort SCBlessUthstinExtendMaxStatsPacket = 0x2BC;
    public const ushort SCBlessUthstinConsumeApplyStatsPacket = 0x163;
    public const ushort SCBlessUthstinApplyStatsPacket = 0x072;
    public const ushort SCAboxBlessUthstinApplyStatsPacket = 0x25D;
    public const ushort SCDoodadOwnershipTimeResetPacket = 0x109;
    public const ushort SCHeirLevelUpPacket = 0x08D;
    public const ushort SCDepartureServerPassportPacket = 0x20E;
    public const ushort SCGoToHomelandPacket = 0x127;
    public const ushort SCHeirSkillListPacket = 0x0A3;
    public const ushort SCActivatedHeirSkillPacket = 0x18A;
    public const ushort SCResetHeirSkillPacket = 0x22B;
    public const ushort SCCharacterPortalsPacket = 0x1C4;
    public const ushort SCCharacterReturnDistrictsPacket = 0x1BF;
    public const ushort SCCharacterLaborPowerChangedPacket = 0x1BB; // SCLaborPowerChangedPacket
    public const ushort SCCharacterBoundPacket = 0x216;
    public const ushort SCKockBackUnitPacket = 0x0B7;
    public const ushort SCItemDetailUpdatedPacket = 0x191;
    public const ushort SCUnitEquipmentsChangedPacket = 0x2BA;
    public const ushort SCCofferContentsPacket = 0x122;
    public const ushort SCItemAcquisitionPacket = 0x2D2;
    public const ushort SCItemGradeEnchantResultPacket = 0x1CD;
    public const ushort SCLinkTextForEnchantBroadcastPacket = 0x1B5;
    public const ushort SCCvFCombatRelationshipPacket = 0xfff; // SCCvfCombatRelationshipPacket
    public const ushort SCAddHousePacket = 0x07F;
    //public const ushort SCChatSpamConfigPacket = 0x2D6;
    public const ushort SCTeamMemberDisconnectedPacket = 0x1D7;
    public const ushort SCZoneGroupStateStartPacket = 0x20C;
    public const ushort SCZoneGroupStateEndPacket = 0x23B;
    public const ushort SCZoneGroupStateScorePacket = 0x1FE;
    public const ushort SCZoneGroupStateBriefingPacket = 0x28F;
    public const ushort SCZoneGroupStateWinnerPacket = 0x114;
    public const ushort SCOtherTradeItemPutupPacket = 0x28E;
    public const ushort SCLootDiceNotifyPacket = 0x2CC;
    public const ushort SCAbilitySetAllInfoPacket = 0x043;
    public const ushort SCDoodadCreatedPacket = 0x26D; // off_39D172C0
    public const ushort SCDoodadsCreatedPacket = 0x210; // off_39D172D8
    public const ushort SCMailBodyPacket = 0x1EF;
    public const ushort SCMateEquipmentChangedPacket = 0x128;
    public const ushort SCSoldItemListPacket = 0x290;
    public const ushort SCAuctionPostedPacket = 0x0E1; // SCAuctionPacket
    public const ushort SCAuctionCanceledPacket = 0x0BB; // SCAuctionPacket
    public const ushort SCPlotEventPacket = 0x247;
    public const ushort SCActabilityPacket = 0x113;
    public const ushort SCGimmicksCreatedPacket = 0x0D9;
    public const ushort off_39D173C8 = 0x24A;
    public const ushort off_39D173F8 = 0x0FC;
    public const ushort off_39D17410 = 0x09D;
    public const ushort off_39D17428 = 0x1A6;
    public const ushort SCPortalSavedPacket = 0x297;
    public const ushort SCOtherTradeItemTookdownPacket = 0x069; // SCOtherTradeitemTookdownPacket
    public const ushort off_39D174AC = 0x0DB;
    public const ushort SCLoadInstancePacket = 0x194; // SCLoadinstancePacket
    public const ushort SCZonePermissionChangedPacket = 0x25F;
    public const ushort SCResponseCommonFarmListPacket = 0x048;
    public const ushort SCTransferTelescopeUnitsPacket = 0x071;
    public const ushort SCBossTelescopeUnitsPacket = 0x181;
    public const ushort SCSchoolOfFishDoodadsPacket = 0x037;
    public const ushort SCExpeditionSummonSuggestPacket = 0x208;
    public const ushort off_39D1769C = 0x02B;
    public const ushort SCUnitAiAggroPacket = 0x0C7;
    public const ushort SCCharacterGenderAndModelModifiedPacket = 0x2B3;
    public const ushort SCAccountAttributeListPacket = 0x0CA; // was SCAccountAttributePacket / off_39D17774
    public const ushort SCAccountAttribute2Packet = 0x2BE; // off_39D17780
    public const ushort off_39D17798 = 0x0BF;
    public const ushort off_39D177A4 = 0x0C2;
    public const ushort SCItemLinkTextForLootPackItemBroadcastPacket = 0x267;
    public const ushort SCGachaLootPackItemResultPacket = 0x2A5;
    public const ushort off_39D1784C = 0x1B8;
    public const ushort SCHousingTradeListPacket = 0x2C8;
    public const ushort SCCreateCharacterResponsePacket = 0x236;
    public const ushort SCEditCharacterResponsePacket = 0x2D7;
    public const ushort CharacterListPacket = 0x076; // was SCCharacterListPacket
    public const ushort SCSlaveEquipmentChangedPacket = 0x203;
    public const ushort SCOneUnitMovementPacket = 0x084;
    public const ushort SCImpulseUnitPacket = 0x16E;
    public const ushort SCMyHousePacket = 0x2D1; // off_39D1B2D8
    public const ushort SCHouseTaxInfoPacket = 0x038;
    public const ushort SCConstructHouseTaxPacket = 0x166;
    public const ushort SCHouseSetForSalePacket = 0x211;
    public const ushort SCJoinedTeamPacket = 0x27B;
    public const ushort SCTeamLootingRuleChangedPacket = 0x29C;
    public const ushort SCSiegeDeclaredPacket = 0x1A4;
    public const ushort SCSiegeSubHqPacket = 0x0C5;
    public const ushort SCQuestsPacket = 0x1EB;
    public const ushort SCLootingBagPacket = 0x1DD;
    public const ushort SCGotMailPacket = 0x080;
    public const ushort SCChargeMoneyPaidPacket = 0x102;
    public const ushort SCAuctionSearchedPacket = 0x219;
    public const ushort SCAuctionLowestPricePacket = 0x0EF; // SCScauctionPacket
    public const ushort SCAuctionMessagePacket = 0x2B4;
    public const ushort SCGimmickMovementPacket = 0x1CB;
    public const ushort SCQuestContextStartedPacket = 0x16C;
    public const ushort SCQuestContextUpdatedPacket = 0x15C;
    public const ushort SCGmDumpQuestsPacket = 0x1E2;
    public const ushort SCGmDumpNpcPacket = 0x0F5;
    public const ushort SCGmDumpMatePacket = 0x0DC;
    public const ushort SCGmDumpSlavePacket = 0x05D;
    public const ushort SCGmDumpMailPacket = 0x07B;
    public const ushort SCGmDumpCharCustomPacket = 0x1C0;
    public const ushort SCTradeMoneyPutupPacket = 0x039;
    public const ushort SCOtherTradeMoneyPutupPacket = 0x03F;
    public const ushort SCTradeMadePacket = 0x167; // off_39D1B410
    public const ushort SCShipyardStatePacket = 0x065;
    public const ushort SCCharDetailPacket = 0x054;
    public const ushort SCLoginCharInfoHousePacket = 0x2D0;
    public const ushort SCTelescopeUnitsPacket = 0x2CE;
    public const ushort off_39D1B44C = 0x035;
    public const ushort SCUnitMovementsPacket = 0x027;
    public const ushort SCItemTaskSuccessPacket = 0x024; // off_39D1B56C
    public const ushort SCUnitBountyMoneyPacket = 0x218;
    public const ushort SCFvFCombatRelationshipPacket = 0x016; // SCFvfCombatRelationshipPacket
    public const ushort SCHouseStatePacket = 0x287;
    public const ushort off_39D1B5A8 = 0x1B4;
    public const ushort SCSetBountyPermittedPacket = 0x1F4;
    public const ushort SCSetBountyDonePacket = 0x1D1;
    public const ushort SCBountyPaidPacket = 0x0C8;
    public const ushort SCUnitStatePacket = 0x204;
    public const ushort SCSiegeStatePacket = 0x164; // off_39D1E894
    public const ushort SCDominionDataPacket = 0x1F8; // off_39D1E8A0
    public const ushort SCGamePointChangedPacket = 0x0f7;
    public const ushort SCNationListPacket = 0x0AA;
    public const ushort SCFactionRelationListPacket = 0x148;
    public const ushort SCFamilyDescPacket = 0x0DF; // SCFamilyDescribedPacket
    public const ushort SCFamilyMemberAddedPacket = 0x2D8;
    public const ushort off_39D1EE28 = 0x207;
    public const ushort SCFamilyCreatedPacket = 0x13F;
    public const ushort CharacterStatePacket = 0x17E; // was SCCharacterStatePacket

    // в версии 3030 в x2game.dll нет таких пакетов
    public const ushort SCFactionCreatedPacket = 0xfff;
    public const ushort SCFactionSetRelationStatePacket = 0xfff;
    public const ushort SCDominionTaxRatePacket = 0xfff;
    public const ushort SCNationalTaxRatePacket = 0xfff;
    public const ushort SCDominionTaxBalancedPacket = 0xfff;
    public const ushort SCCharBriefPacket = 0xfff;
    public const ushort SCPlaytimePacket = 0xfff;
    public const ushort SCPortalInfoSavedPacket = 0xfff;
    public const ushort SCItemSocketingLunagemResultPacket = 0xfff;
    public const ushort SCItemSocketingLunastoneResultPacket = 0xfff;
    public const ushort SCGradeEnchantBroadcastPacket = 0xfff;
    public const ushort SCHouseBuildPayChangedPacket = 0xfff;
    public const ushort SCTeamBecameRaidTeamPacket = 0xfff;
    public const ushort SCAttachmentTakenPacket = 0xfff;
    public const ushort SCBondDoodadPacket = 0x205; // SCAttachToDoodadPacket
    public const ushort SCUnbondDoodadPacket = 0x06a; //SCDetachFromDoodadPacket
    public const ushort SCTradeOkUpdatePacket = 0xfff; // SCOtherTradeOkPacket
    public const ushort SCChangeJuryOKCountPacket = 0xfff;
    public const ushort SCChangeJuryVerdictCountPacket = 0xfff;
    public const ushort SCTrialAudienceJoinedPacket = 0xfff;
    public const ushort SCTrialAudienceLeftPacket = 0xfff;
    //public const ushort SCAuctionLowestPricePacket = 0xfff; // SCAuctionPacket
    public const ushort SCSkillUpgradedPacket = 0xfff;
    public const ushort SCTrialCancledPacket = 0xfff;
    public const ushort SCExpeditionRoleChangedPacket = 0xfff;
    public const ushort SCItemUccDataChangedPacket = 0xfff; // SCItemUccChangedPacket
    public const ushort SCCofferContentsUpdatePacket = 0xfff; // SCCofferContentsPacket
    public const ushort SCResultRestrictCheckPacket = 0x281;
    //public const ushort SCSpecialtyRatioPacket = 0xfff;
    public const ushort SCTeamMemberRoleChangedPacket = 0xfff;
    //public const ushort SCAuctionCanceledPacket = 0xfff;
    //public const ushort SCCharacterLaborPowerChangedPacket = 0xfff;
    public const ushort SCHousingRecoverTogglePacket = 0xfff;
    public const ushort SCKnockBackUnitPacket = 0xfff;
    public const ushort SCLootDicePacket = 0xfff;
    public const ushort SCAggroTargetChanged = 0xfff;
    public const ushort SCOnOffSnowPacket = 0xfff; // custom 1.2 packet; no 3.5 opcode
    public const ushort SCShowCommonFarmPacket = 0xfff;
    public const ushort SCSlaveStatePacket = 0xfff;
    public const ushort SCSuspectGoingBotTrial = 0xfff;
    public const ushort SCTeleportUnitPacket = 0xfff;
    public const ushort SCToggleBeautyshopResponsePacket = 0xfff;
    public const ushort SCUnitOfflinePacket = 0xfff;
    public const ushort SCUnknownPacket = 0xfff;
    public const ushort SCUserNoteLoadedPacket = 0xfff;
    public const ushort SCAiAggroPacket = 0x0C7;
    public const ushort SCCancelCharacterDeleteResponsePacket = 0x183;
    //public const ushort SCChatSpamDelayPacket = 0x2D6;
    public const ushort SCCrimeChangedPacket = 0xfff;
    public const ushort SCDeleteCharacterResponsePacket = 0x2A2;
    public const ushort SCDoodadQuestAcceptPacket = 0xfff;
    public const ushort SCGradeEnchantResultPacket = 0xfff;
    public const ushort SCInstantGameAddPointPacket = 0xfff;
    public const ushort SCInstantGameUnkPacket = 0xfff;
    public const ushort SCInvenExpandedPacket = 0xfff;
    public const ushort SCLootBagDataPacket = 0xfff;
    public const ushort SCLpManagedPacket = 0xfff;
    public const ushort SCMateStatePacket = 0xfff;
    public const ushort SCMyHouseRemovedPacket = 0xfff;
    //public const ushort SCMailFailedPacket = 0xfff;
    //public const ushort SCMineAmountPacket = 0xfff;
}
