namespace AAEmu.Game.Core.Packets.G2C;

public static class SCOffsets
{
    public const ushort X2EnterWorldResponsePacket = 0x00;
    public const ushort SCReconnectAuthPacket = 0x1;
    public const ushort SCPrepareLeaveWorldPacket = 0x2;
    public const ushort SCLeaveWorldGrantedPacket = 0x3;
    public const ushort SCLeaveWorldCanceledPacket = 0x4;
    public const ushort SCWorldQueuePacket = 0x5;
    public const ushort SCInitialConfigPacket = 0x7;
    public const ushort SCTrionConfigPacket = 0x07;
    public const ushort SCExpeditionListPacket = 0xA; // 10.0.2.13
    public const ushort SCFactionRelationListPacket = 0xB; // 10.0.2.13
    public const ushort SCExpeditionRolePolicyListPacket = 0xD; // 10.0.2.13
    public const ushort SCExpeditionRolePolicyChangedPacket = 0xE; // 10.0.2.13
    public const ushort SCExpeditionRoleChangedPacket = 0xF; // 10.0.2.13
    public const ushort SCExpeditionOwnerChangedPacket = 0x10; // 10.0.2.13
    public const ushort SCExpeditionShowRenameUIPacket = 0x11; // 10.0.2.13
    public const ushort SCNationShowRenameUIPacket = 0x10;
    public const ushort SCFactionRenamedPacket = 0x12; // 10.0.2.13
    public const ushort SCFactionRetryRenamePacket = 0x13; // 10.0.2.13
    public const ushort SCFactionCreatedPacket = 0x13;
    public const ushort SCExpeditionSponsorChangedPacket = 0x16; // 10.0.2.13
    public const ushort SCExpeditionDismissedPacket = 0x17; // 10.0.2.13
    public const ushort SCExpeditionMemberListPacket = 0x23; // 10.0.2.13
    public const ushort SCExpeditionMemberStatusChangedPacket = 0x25; // 10.0.2.13
    public const ushort SCFactionOwnerChangedPacket = 0x18;
    public const ushort SCFactionSetRelationStatePacket = 0x28; // 10.0.2.13
    public const ushort SCExpeditionInvitationPacket = 0x2D; // 10.0.2.13
    public const ushort SCUnitFactionChangedPacket = 0x2E; // 10.0.2.13 (10.0.2.13 name: UnitFactionChangedPacket)
    public const ushort SCUnitExpeditionChangedPacket = 0x2F; // 10.0.2.13 (10.0.2.13 name: UnitExpeditionChangedPacket)
    public const ushort SCDominionDataPacket = 0x30; // 10.0.2.13
    public const ushort SCDominionDeletedPacket = 0x32; // 10.0.2.13
    public const ushort SCDominionOwnerChangedPacket = 0x33; // 10.0.2.13
    public const ushort SCDominionTaxRatePacket = 0x34; // 10.0.2.13
    public const ushort SCNationalTaxRatePacket = 0x21;
    public const ushort SCNationalMonumentChangedPacket = 0x22;
    public const ushort SCDominionTaxBalancedPacket = 0x23;
    public const ushort CDominionStartUnkPacket = 0x24;
    public const ushort SCDominionEndUnkPacket = 0x25;
    public const ushort SCFactionIndependencePacket = 0x26;
    public const ushort SCFactionImmigrateInvitePacket = 0x27;
    public const ushort SCFactionImmigrateInviteResultPacket = 0x28;
    public const ushort SCFactionImmigrateToOriginResultPacket = 0x29;
    public const ushort SCFactionKickToOriginResultPacket = 0x2a;
    public const ushort SCFactionDeclareHostileResultPacket = 0x2b;
    public const ushort SCFactionRelationExpiredPacket = 0x2c;
    public const ushort SCFamilyInvitationPacket = 0x52; // 10.0.2.13
    public const ushort SCFamilyCreatedPacket = 0x53; // 10.0.2.13
    public const ushort SCFamilyRemovedPacket = 0x54; // 10.0.2.13
    public const ushort SCFamilyDescPacket = 0x55; // 10.0.2.13
    public const ushort SCFamilyMemberAddedPacket = 0x56; // 10.0.2.13
    public const ushort SCFamilyMemberRemovedPacket = 0x57; // 10.0.2.13
    public const ushort SCFamilyOwnerChangedPacket = 0x58; // 10.0.2.13
    public const ushort SCFamilyTitleChangedPacket = 0x59; // 10.0.2.13
    public const ushort SCFamilyMemberNameChangedPacket = 0x5A; // 10.0.2.13
    public const ushort SCFamilyTitlePacket = 0x5B; // 10.0.2.13
    public const ushort SCFamilyMemberOnlinePacket = 0x5C; // 10.0.2.13
    public const ushort SCCreateCharacterResponsePacket = 0x63; // 10.0.2.13 (10.0.2.13 name: CreateCharacterResponsePacket)
    public const ushort SCDeleteCharacterResponsePacket = 0x64; // 10.0.2.13 (10.0.2.13 name: DeleteCharacterResponsePacket)
    public const ushort SCEditCharacterResponsePacket = 0x65; // 10.0.2.13
    public const ushort SCCharacterDeletedPacket = 0x66; // 10.0.2.13
    public const ushort SCCancelCharacterDeleteResponsePacket = 0x67; // 10.0.2.13 (10.0.2.13 name: CancelCharacterDeleteResponsePacket)
    public const ushort SCCharacterCreationFailedPacket = 0x68; // 10.0.2.13 (10.0.2.13 name: CharacterCreationFailedPacket)
    public const ushort SCCharacterListPacket = 0x69;
    public const ushort SCCheckRaceCongestionResponsePacket = 0x6A;
    public const ushort SCRaceCongestionPacket = 0x6B;
    public const ushort SCCharacterStatePacket = 0x6C; // 10.0.2.13 (10.0.2.13 name: CharacterStatePacket)
    public const ushort SCNotifyResurrectionPacket = 0x6D; // 10.0.2.13
    public const ushort SCCharacterResurrectedPacket = 0x6E; // 10.0.2.13 (10.0.2.13 name: CharacterResurrectedPacket)
    public const ushort SCForceAttackSetPacket = 0x6F; // 10.0.2.13
    public const ushort SCCharacterLaborPowerChangedPacket = 0x70; // 10.0.2.13
    public const ushort SCBmPointPacket = 0x71; // 10.0.2.13
    public const ushort SCAddActionPointPacket = 0x72; // 10.0.2.13
    public const ushort SCLpManagedPacket = 0x73; // 10.0.2.13
    public const ushort SCCharacterBoundPacket = 0x74; // 10.0.2.13
    public const ushort SCCooldownsPacket = 0x75; // 10.0.2.13
    public const ushort SCCharacterInvenInitPacket = 0x76; // 10.0.2.13
    public const ushort SCCharacterInvenContentsPacket = 0x77; // 10.0.2.13
    public const ushort SCInvenExpandedPacket = 0x78; // 10.0.2.13
    public const ushort SCFriendsPacket = 0x7A; // 10.0.2.13
    public const ushort SCSearchListPacket = 0x7B; // 10.0.2.13
    public const ushort SCDeleteFriendPacket = 0x7C; // 10.0.2.13
    public const ushort SCFriendStatusChangedPacket = 0x7D; // 10.0.2.13
    public const ushort SCCharDetailPacket = 0x7E; // 10.0.2.13
    public const ushort SCBlockedUsersPacket = 0x7F; // 10.0.2.13
    public const ushort SCAddBlockedUserPacket = 0x80; // 10.0.2.13
    public const ushort SCDeleteBlockedUserPacket = 0x81; // 10.0.2.13
    public const ushort SCLoginCharInfoHousePacket = 0x57;
    public const ushort SCCharBriefPacket = 0x82; // 10.0.2.13
    public const ushort SCPlaytimePacket = 0x83;  // 10.0.2.13
    public const ushort SCCharacterRenamedPacket = 0x84; // 10.0.2.13
    // Portals=136, ReturnDistricts=137, PortalInfoSaved=138, PortalDeleted=139.
    // The old 0x5b/0x5c values collided with SCFamilyTitle / SCFamilyMemberOnline,
    // so discovered districts never reached the client's book UI.
    public const ushort SCCharacterPortalsPacket = 0x88; // 10.0.2.13
    public const ushort SCCharacterReturnDistrictsPacket = 0x89; // 10.0.2.13
    public const ushort SCPortalInfoSavedPacket = 0x8A; // 10.0.2.13
    public const ushort SCPortalDeletedPacket = 0x8B; // 10.0.2.13
    public const ushort SCUnitPortalUsedPacket = 0x8C; // 10.0.2.13
    public const ushort SCSlaveCreatedPacket = 0x8E; // 10.0.2.13
    public const ushort SCSlaveRemovedPacket = 0x8F; // 10.0.2.13
    public const ushort SCSlaveDespawnPacket = 0x90; // 10.0.2.13
    public const ushort SCSlaveBoundPacket = 0x91; // 10.0.2.13
    public const ushort SCQuestListPacket = 0x195; // 10.0.2.13
    public const ushort SCMySlavePacket = 0x92; // 10.0.2.13
    public const ushort SCEscapeSlavePacket = 0x93; // 10.0.2.13
    public const ushort SCSlaveEquipmentChangedPacket = 0x95; // 10.0.2.13
    public const ushort SCUnitStatePacket = 0x97; // 10.0.2.13 (10.0.2.13 name: UnitStatePacket)
    public const ushort SCUnitsRemovedPacket = 0x98; // 10.0.2.13
    public const ushort SCUnitMovementsPacket = 0x99; // 10.0.2.13
    public const ushort SCOneUnitMovementPacket = 0x9A; // 10.0.2.13
    public const ushort SCSkillControllerStatePacket = 0x9D; // 10.0.2.13
    public const ushort SCUnitOfflinePacket = 0x9E; // 10.0.2.13
    public const ushort SCActiveWeaponChangedPacket = 0x9F; // 10.0.2.13
    public const ushort SCUnitNameChangedPacket = 0xA0; // 10.0.2.13
    public const ushort SCUnitDeathPacket = 0xA1; // 10.0.2.13 (10.0.2.13 name: UnitDeathPacket)
    public const ushort SCTeleportUnitPacket = 0xA2; // 10.0.2.13
    public const ushort SCBlinkUnitPacket = 0xA3; // 10.0.2.13
    public const ushort SCKnockBackUnitPacket = 0xA4; // 10.0.2.13
    public const ushort SCUnitAttachedPacket = 0xA5; // 10.0.2.13 (10.0.2.13 name: UnitAttachedPacket)
    public const ushort SCUnitDetachedPacket = 0xA6; // 10.0.2.13 (10.0.2.13 name: UnitDetachedPacket)
    public const ushort SCUnitInvisiblePacket = 0xA7; // 10.0.2.13
    public const ushort SCUnitImpulsePacket = 0xA8; // 10.0.2.13
    public const ushort SCUnitFlyingStateChangedPacket = 0xA9; // 10.0.2.13
    public const ushort SCNpcInteractionSkillListPacket = 0xAA; // 10.0.2.13
    public const ushort SCNpcInteractionEndedByZonePacket = 0xAB; // 10.0.2.13
    public const ushort SCWorldInteractionSkillListPacket = 0xAC; // 10.0.2.13
    public const ushort SCWorldInteractionCanceledPacket = 0xAD; // 10.0.2.13
    public const ushort SCNpcInteractionStatusChangedPacket = 0xAE; // 10.0.2.13
    public const ushort SCVegetationCutdowningPacket = 0xAF; // 10.0.2.13
    public const ushort SCNpcFriendshipListPacket = 0x82;
    public const ushort SCNpcFriendshipChangedPacket = 0x83;
    public const ushort SCTargetChangedPacket = 0xB0; // 10.0.2.13 (10.0.2.13 name: TargetChangedPacket)
    public const ushort SCCombatEngagedPacket = 0xB1; // 10.0.2.13
    public const ushort SCCombatClearedPacket = 0xB2; // 10.0.2.13
    public const ushort SCCvFCombatRelationshipPacket = 0xB3; // 10.0.2.13
    public const ushort SCFvFCombatRelationshipPacket = 0xB4; // 10.0.2.13
    public const ushort SCCombatFirstHitPacket = 0xB5; // 10.0.2.13
    public const ushort SCDumpCombatStatPacket = 0xB6;  // 10.0.2.13
    public const ushort SCDuelChallengedPacket = 0xB7; // 10.0.2.13
    public const ushort SCDuelStartCountdownPacket = 0xB8; // 10.0.2.13
    public const ushort SCDuelStartedPacket = 0xB9; // 10.0.2.13
    public const ushort SCDuelEndedPacket = 0xBA; // 10.0.2.13
    public const ushort SCDuelStatePacket = 0xBB; // 10.0.2.13
    public const ushort SCItemTaskSuccessPacket = 0xBC; // 10.0.2.13
    public const ushort SCItemTaskNotifyPacket = 0xBD; // 10.0.2.13
    public const ushort SCItemDetailUpdatedPacket = 0xBE; // 10.0.2.13
    public const ushort SCUnitEquipmentsChangedPacket = 0xBF; // 10.0.2.13
    public const ushort SCUnitEquipmentsRndAttrUnitModifierActivatedPacket = 0xC0; // 10.0.2.13
    public const ushort SCUnitEquipmentIdsPacket = 0xC1; // 10.0.2.13
    public const ushort SCCofferContentsUpdatePacket = 0xC2; // 10.0.2.13
    public const ushort SCItemAcquisitionPacket = 0xC3; // 10.0.2.13
    public const ushort SCSyncItemLifespanPacket = 0xC4; // 10.0.2.13
    public const ushort SCSpecialtyRatioPacket = 0xC5; // 10.0.2.13
    public const ushort SCSpecialtyGoodsPacket = 0xC6; // 10.0.2.13
    public const ushort SCSpecialtyRecordsPacket = 0xC7; // 10.0.2.13
    public const ushort SCGradeEnchantResultPacket = 0xC9; // 10.0.2.13
    public const ushort SCItemSocketingLunastoneResultPacket = 0x9e;
    public const ushort SCGradeEnchantBroadcastPacket = 0xD0; // 10.0.2.13
    public const ushort SCUnknownPacket = 0xa0;
    public const ushort SCSkillStartedPacket = 0xD7; // 10.0.2.13 (10.0.2.13 name: SkillStartedPacket)
    public const ushort SCSkillFiredPacket = 0xD8; // 10.0.2.13 (10.0.2.13 name: SkillFiredPacket)
    public const ushort SCSkillEndedPacket = 0xD9; // 10.0.2.13 (10.0.2.13 name: SkillEndedPacket)
    public const ushort SCSkillStoppedPacket = 0xDA; // 10.0.2.13 (10.0.2.13 name: SkillStoppedPacket)
    public const ushort SCCastingStoppedPacket = 0xDB; // 10.0.2.13
    public const ushort SCCastingDelayedPacket = 0xDC; // 10.0.2.13
    public const ushort SCUnitDamagedPacket = 0xDD; // 10.0.2.13 (10.0.2.13 name: UnitDamagedPacket)
    public const ushort SCUnitHealedPacket = 0xDE; // 10.0.2.13 (10.0.2.13 name: UnitHealedPacket)
    public const ushort SCUnitTrackedPacket = 0xDF; // 10.0.2.13
    public const ushort SCBombUpdatedPacket = 0xE0; // 10.0.2.13
    public const ushort SCCombatTextPacket = 0xE1; // 10.0.2.13
    public const ushort SCSkillCooldownResetPacket = 0xE2; // 10.0.2.13
    public const ushort SCPlotEventPacket = 0xE3;  // 10.0.2.13
    public const ushort SCPlotEndedPacket = 0xE4; // 10.0.2.13
    public const ushort SCPlotProcessingTimePacket = 0xE5;  // 10.0.2.13
    public const ushort SCPlotCastingStoppedPacket = 0xE6; // 10.0.2.13
    public const ushort SCPlotChannelingStoppedPacket = 0xE7; // 10.0.2.13
    public const ushort SCEnvDamagePacket = 0xE8; // 10.0.2.13
    public const ushort SCOnOffSnowPacket = 0xb4;
    public const ushort SCUnkPacket = 0xb5;
    public const ushort SCBuffCreatedPacket = 0xEB; // 10.0.2.13
    public const ushort SCBuffRemovedPacket = 0xEC; // 10.0.2.13
    public const ushort SCBuffUpdatedPacket = 0xEE; // 10.0.2.13
    public const ushort SCUnitPointsPacket = 0xEF; // 10.0.2.13
    public const ushort SCUnitBountyMoneyPacket = 0xbb;
    public const ushort SCHouseStatePacket = 0xF0; // 10.0.2.13
    public const ushort SCHouseBuildProgressPacket = 0xF1; // 10.0.2.13
    public const ushort SCHousePermissionChangedPacket = 0xF2; // 10.0.2.13
    public const ushort SCHouseBuildPayChangedPacket = 0xbf;
    public const ushort SCHouseDemolishedPacket = 0xF3; // 10.0.2.13
    public const ushort SCHouseDataPacket = 0xF4; // 10.0.2.13
    public const ushort SCHouseRemovedPacket = 0xF5; // 10.0.2.13
    public const ushort SCHouseFarmPacket = 0xF6; // 10.0.2.13
    public const ushort SCHouseTaxInfoPacket = 0xF7; // 10.0.2.13
    public const ushort SCConstructHouseTaxPacket = 0xF8; // 10.0.2.13
    public const ushort SCHousingRecoverTogglePacket = 0xF9; // 10.0.2.13
    public const ushort SCHouseSetForSalePacket = 0xFA; // 10.0.2.13
    public const ushort SCHouseResetForSalePacket = 0xFB; // 10.0.2.13
    public const ushort SCHouseSoldPacket = 0xFC; // 10.0.2.13
    public const ushort SCHouseOwnerNameChangedPacket = 0xFD; // 10.0.2.13
    public const ushort SCJoinedChatChannelPacket = 0x100; // 10.0.2.13
    public const ushort SCLeavedChatChannelPacket = 0x101; // 10.0.2.13
    public const ushort SCChatMessagePacket = 0x102; // 10.0.2.13
    public const ushort SCNpcChatMessagePacket = 0x103; // 10.0.2.13
    public const ushort SCNoticeMessagePacket = 0x104; // 10.0.2.13
    public const ushort SCChatFailedPacket = 0x105; // 10.0.2.13
    public const ushort SCChatLocalizedMessagePacket = 0x106; // 10.0.2.13
    public const ushort SCChatSpamDelayPacket = 0x107; // 10.0.2.13 SCChatSpamConfig (1.2 was 0xd3)
    public const ushort SCAskToJoinTeamPacket = 0x109; // 10.0.2.13
    public const ushort SCAskToJoinTeamAreaPacket = 0x10A; // 10.0.2.13
    public const ushort SCJoinedTeamPacket = 0x10B; // 10.0.2.13
    public const ushort SCRejectedTeamPacket = 0x10C; // 10.0.2.13
    public const ushort SCLeavedTeamPacket = 0x10D; // 10.0.2.13
    public const ushort SCTeamDismissedPacket = 0x10E; // 10.0.2.13
    public const ushort SCTeamMemberJoinedPacket = 0x10F; // 10.0.2.13
    public const ushort SCTeamMemberLeavedPacket = 0x110; // 10.0.2.13
    public const ushort SCTeamMemberDisconnectedPacket = 0x111; // 10.0.2.13
    public const ushort SCTeamOwnerChangedPacket = 0x112; // 10.0.2.13
    public const ushort SCTeamMemberRoleChangedPacket = 0x113; // 10.0.2.13
    public const ushort SCTeamBecameRaidTeamPacket = 0x114; // 10.0.2.13
    public const ushort SCTeamMemberMovedPacket = 0x115; // 10.0.2.13
    public const ushort SCTeamLootingRuleChangedPacket = 0x116; // 10.0.2.13
    public const ushort SCRefreshTeamMemberPacket = 0x117; // 10.0.2.13
    public const ushort SCTeamRemoteMembersExPacket = 0x118; // 10.0.2.13
    public const ushort SCTeamAreaInvitedPacket = 0x119; // 10.0.2.13
    public const ushort SCOverHeadMarkerSetPacket = 0x11A; // 10.0.2.13
    public const ushort SCTeamPingPosPacket = 0x11B; // 10.0.2.13
    public const ushort SCTeamAckRiskyActionPacket = 0x11C; // 10.0.2.13
    public const ushort SCTeamAskHandOverOwnerPacket = 0x11D; // 10.0.2.13
    public const ushort SCTeamAskAcceptOwnerOfferPacket = 0x11E; // 10.0.2.13
    public const ushort SCTeamHandOverOwnerOfferResultPacket = 0x11F; // 10.0.2.13
    public const ushort SCSiegeStatePacket = 0x128; // 10.0.2.13
    public const ushort SCSiegeDeclaredPacket = 0x129; // 10.0.2.13
    public const ushort SCSiegeReinforcePacket = 0xeb;
    public const ushort SCSiegeMemberPacket = 0x12A; // 10.0.2.13
    public const ushort SCSiegeAlertPacket = 0x12B; // 10.0.2.13
    public const ushort SCConflictZoneStatePacket = 0x12D; // 10.0.2.13
    public const ushort SCConflictZoneHonorPointSumPacket = 0x12E; // 10.0.2.13
    public const ushort SCTimeOfDayPacket = 0x130; // 10.0.2.13 (10.0.2.13 name: TimeOfDayPacket)
    public const ushort SCDetailedTimeOfDayPacket = 0x131; // 10.0.2.13 (10.0.2.13 name: DetailedTimeOfDayPacket)
    public const ushort SCQuestsPacket = 0x132; // 10.0.2.13 SC_PACKET_QUESTS (306)
    public const ushort SCCompletedQuestsPacket = 0x133; // 10.0.2.13
    public const ushort SCCraftItemUnlockPacket = 0x134; // 10.0.2.13
    public const ushort SCLootableStatePacket = 0x135; // 10.0.2.13
    public const ushort SCUnitLootingStatePacket = 0x136; // 10.0.2.13
    public const ushort SCLootBagDataPacket = 0x137; // 10.0.2.13
    public const ushort SCLootItemTookPacket = 0x138; // 10.0.2.13
    public const ushort SCLootItemFailedPacket = 0x139; // 10.0.2.13
    public const ushort SCLootDicePacket = 0x13A; // 10.0.2.13
    public const ushort SCLootDiceNotifyPacket = 0x13B; // 10.0.2.13
    public const ushort SCLootDiceSummaryPacket = 0x13C; // 10.0.2.13
    public const ushort SCExpChangedPacket = 0x13D; // 10.0.2.13
    public const ushort SCAbilityExpChangedPacket = 0x13E; // 10.0.2.13
    public const ushort SCRecoverableExpPacket = 0x13F; // 10.0.2.13
    public const ushort SCMileageChangedPacket = 0x101;
    public const ushort SCLevelChangedPacket = 0x140; // 10.0.2.13
    public const ushort SCUnitModelPostureChangedPacket = 0x142; // 10.0.2.13 (10.0.2.13 name: UnitModelPostureChangedPacket)
    public const ushort SCSkillLearnedPacket = 0x143; // 10.0.2.13
    public const ushort SCSkillUpgradedPacket = 0x106;
    public const ushort SCBuffLearnedPacket = 0x144; // 10.0.2.13
    public const ushort SCSkillsResetPacket = 0x145; // 10.0.2.13
    public const ushort SCAbilitySwappedPacket = 0x147; // 10.0.2.13
    public const ushort SCErrorMsgPacket = 0x14D; // 10.0.2.13 (10.0.2.13 name: ErrorMsgPacket)
    public const ushort SCDoodadCreatedPacket = 0x14E; // 10.0.2.13 (10.0.2.13 name: DoodadCreatedPacket)
    public const ushort SCDoodadRemovedPacket = 0x14F; // 10.0.2.13 (10.0.2.13 name: DoodadRemovedPacket)
    public const ushort SCDoodadChangedPacket = 0x150; // 10.0.2.13 (10.0.2.13 name: DoodadChangedPacket)
    public const ushort SCDoodadPhaseChangedPacket = 0x151; // 10.0.2.13
    public const ushort SCDoodadPuzzleScenePacket = 0x152; // 10.0.2.13
    public const ushort SCDoodadQuestAcceptPacket = 0x153; // 10.0.2.13
    public const ushort SCDoodadsCreatedPacket = 0x154; // 10.0.2.13
    public const ushort SCDoodadsRemovedPacket = 0x155; // 10.0.2.13
    public const ushort SCDoodadOriginatorPacket = 0x156; // 10.0.2.13
    public const ushort SCMailFailedPacket = 0x15A; // 10.0.2.13
    public const ushort SCMailSentPacket = 0x15C; // 10.0.2.13
    public const ushort SCGotMailPacket = 0x15D; // 10.0.2.13
    public const ushort SCCountTotalMailPacket = 0x15B; // 10.0.2.13
    public const ushort SCMailListPacket = 0x15E; // 10.0.2.13
    public const ushort SCMailListEndPacket = 0x15F; // 10.0.2.13
    public const ushort SCMailBodyPacket = 0x160; // 10.0.2.13
    public const ushort SCMailReceiverOpenedPacket = 0x161; // 10.0.2.13
    public const ushort SCAttachmentTakenPacket = 0x162; // 10.0.2.13
    public const ushort SCChargeMoneyPaidPacket = 0x163; // 10.0.2.13
    public const ushort SCMailDeletedPacket = 0x164; // 10.0.2.13
    public const ushort SCSpamReportedPacket = 0x120;
    public const ushort SCMailReturnedPacket = 0x165; // 10.0.2.13
    public const ushort SCMailStatusUpdatedPacket = 0x166; // 10.0.2.13
    public const ushort SCMailRemovedPacket = 0x167; // 10.0.2.13
    public const ushort SCMineAmountPacket = 0x169;  // 10.0.2.13
    public const ushort SCMateSpawnedPacket = 0x16A; // 10.0.2.13
    public const ushort SCMateEquipmentChangedPacket = 0x16B; // 10.0.2.13
    public const ushort SCMateEquipmentExpiredPacket = 0x16C; // 10.0.2.13
    public const ushort SCUnkPacket4 = 0x128;
    public const ushort SCEmotionExpressedPacket = 0x16E; // 10.0.2.13
    public const ushort SCSoldItemListPacket = 0x16F; // 10.0.2.13
    public const ushort SCActionSlotsPacket = 0x170; // 10.0.2.13
    public const ushort SCAuctionPostedPacket = 0x171; // 10.0.2.13
    public const ushort SCAuctionSearchedPacket = 0x172; // 10.0.2.13
    public const ushort SCAuctionLowestPricePacket = 0x173; // 10.0.2.13
    public const ushort SCAuctionBidPacket = 0x174; // 10.0.2.13
    public const ushort SCAuctionCanceledPacket = 0x175; // 10.0.2.13
    public const ushort SCAuctionMessagePacket = 0x176; // 10.0.2.13
    public const ushort SCDiceValuePacket = 0x179; // 10.0.2.13
    public const ushort SCDiceBidRuleChangedPacket = 0x17A; // 10.0.2.13
    public const ushort SCNpcSpawnerPacket = 0x135;
    public const ushort SCActabilityPacket = 0x17B; // 10.0.2.13
    public const ushort SCHungPacket = 0x17C; // 10.0.2.13
    public const ushort SCUnhungPacket = 0x17D; // 10.0.2.13
    public const ushort SCBondDoodadPacket = 0x17E; // 10.0.2.13
    public const ushort SCUnbondDoodadPacket = 0x17F; // 10.0.2.13
    public const ushort SCPlaySequencePacket = 0x180; // 10.0.2.13
    // (112-byte stride) places SCGimmicksCreatedPacket between SCPlaySequencePacket (0x180) and
    // SCGimmicksRemovedPacket (0x182).
    public const ushort SCGimmicksCreatedPacket = 0x181; // 10.0.2.13
    public const ushort SCGimmicksRemovedPacket = 0x182; // 10.0.2.13
    public const ushort SCGimmickMovementPacket = 0x183; // 10.0.2.13
    public const ushort SCGimmickJointsBrokenPacket = 0x184; // 10.0.2.13
    public const ushort SCGimmickResetJointsPacket = 0x185; // 10.0.2.13
    public const ushort SCGimmickGraspedPacket = 0x186; // 10.0.2.13
    public const ushort SCWorldRayCastingResultPacket = 0x187; // 10.0.2.13
    public const ushort SCWorldAimPointPacket = 0x188;  // 10.0.2.13
    public const ushort SCWorldAABBPacket = 0x189;  // 10.0.2.13
    public const ushort SCUnkPacket5 = 0x145;
    public const ushort SCQuestContextFailedPacket = 0x18B; // 10.0.2.13
    public const ushort SCQuestContextStartedPacket = 0x18C; // 10.0.2.13
    public const ushort SCQuestUnitReqFailedPacket = 0x18D; // 10.0.2.13
    public const ushort SCQuestContextUpdatedPacket = 0x18E; // 10.0.2.13
    public const ushort CSQuestAcceptConditionalPacket = 0x14a;
    public const ushort SCQuestContextCompletedPacket = 0x190; // 10.0.2.13
    public const ushort SCQuestContextResetPacket = 0x191; // 10.0.2.13
    public const ushort SCQuestContextResetBulkPacket = 0x192; // 10.0.2.13
    public const ushort SCDoodadCompleteQuestPacket = 0x193; // 10.0.2.13
    public const ushort SCQuestRewardedByMailPacket = 0x194; // 10.0.2.13
    public const ushort SCQuestMailSentPacket = 0x196; // 10.0.2.13
    public const ushort SCScheduleItemSentPacket = 0x197; // 10.0.2.13
    public const ushort SCSoundAreaEventPacket = 0x198; // 10.0.2.13
    public const ushort SCAreaChatBubblePacket = 0x199; // 10.0.2.13
    public const ushort SCChatBubblePacket = 0x19A; // 10.0.2.13
    public const ushort SCAreaTeamMessagePacket = 0x19B; // 10.0.2.13
    public const ushort SCDoodadSoundPacket = 0x19C; // 10.0.2.13
    public const ushort SCDoodadPhaseMsgPacket = 0x19D; // 10.0.2.13
    public const ushort SCDoodadUccStringPacket = 0x1A0; // 10.0.2.13
    public const ushort SCDoodadUccDataPacket = 0x1A1; // 10.0.2.13
    public const ushort SCUccCharacterNameLoadedPacket = 0x1A2; // 10.0.2.13
    public const ushort SCNaviTeleportPacket = 0x1A3; // 10.0.2.13
    public const ushort SCItemUccDataChangedPacket = 0x1A4; // 10.0.2.13
    public const ushort SCCanStartTradePacket = 0x1A5; // 10.0.2.13
    public const ushort SCCannotStartTradePacket = 0x1A6; // 10.0.2.13
    public const ushort SCTradeStartedPacket = 0x1A7; // 10.0.2.13
    public const ushort SCTradeCanceledPacket = 0x1A8; // 10.0.2.13
    public const ushort SCTradeItemPutupPacket = 0x1A9; // 10.0.2.13
    public const ushort SCOtherTradeItemPutupPacket = 0x1AA; // 10.0.2.13
    public const ushort SCTradeMoneyPutupPacket = 0x1AB; // 10.0.2.13
    public const ushort SCOtherTradeMoneyPutupPacket = 0x1AC; // 10.0.2.13
    public const ushort SCTradeItemTookdownPacket = 0x1AD; // 10.0.2.13
    public const ushort SCOtherTradeItemTookdownPacket = 0x1AE; // 10.0.2.13
    public const ushort SCTradeOkUpdatePacket = 0x1AF; // 10.0.2.13
    public const ushort SCTradeLockUpdatePacket = 0x1B0; // 10.0.2.13
    public const ushort SCTradeMadePacket = 0x1B1; // 10.0.2.13
    public const ushort SCTowerDefListPacket = 0x1B2;  // 10.0.2.13
    public const ushort SCTowerDefStartPacket = 0x1B3; // 10.0.2.13
    public const ushort SCTowerDefEndPacket = 0x1B4; // 10.0.2.13
    public const ushort SCTowerDefWaveStartPacket = 0x1B5; // 10.0.2.13
    /// <summary>World-map tower marks; rebuilds client active list (Crimson red skull / icon_key).</summary>
    public const ushort SCTowerDefActiveInfoListPacket = 0x344; // 10.0.2.13
    public const ushort SCCrimeChangedPacket = 0x1B6; // 10.0.2.13
    public const ushort SCCriminalArrestedPacket = 0x1B7; // 10.0.2.13
    public const ushort SCAskImprisonOrTrialPacket = 0x1B8; // 10.0.2.13
    public const ushort SCInviteJuryPacket = 0x1B9; // 10.0.2.13
    public const ushort SCSummonJuryPacket = 0x1BA; // 10.0.2.13
    public const ushort SCJuryBeSeatedPacket = 0x1BB; // 10.0.2.13
    public const ushort SCSummonDefendantPacket = 0x1BC; // 10.0.2.13
    public const ushort SCCrimeDataPacket = 0x1BD; // 10.0.2.13
    public const ushort SCCrimeRecordsPacket = 0x1BE; // 10.0.2.13
    public const ushort SCChangeTrialStatePacket = 0x1BF; // 10.0.2.13
    public const ushort SCChangeJuryOKCountPacket = 0x1C0; // 10.0.2.13
    public const ushort SCChangeJuryVerdictCountPacket = 0x1C1; // 10.0.2.13
    public const ushort SCTrialWaitStatusPacket = 0x1C2; // 10.0.2.13
    public const ushort SCJuryWaitStatusPacket = 0x1C3; // 10.0.2.13
    public const ushort SCRulingStatusPacket = 0x1C4; // 10.0.2.13
    public const ushort SCRulingClosedPacket = 0x1C5; // 10.0.2.13
    public const ushort SCTrialAudienceJoinedPacket = 0x1C6; // 10.0.2.13
    public const ushort SCTrialAudienceLeftPacket = 0x1C7; // 10.0.2.13
    public const ushort SCTrialInfoPacket = 0x1C8; // 10.0.2.13
    public const ushort SCJuryWaitingNumberPacket = 0x1C9; // 10.0.2.13
    public const ushort SCTrialCancledPacket = 0x1CA; // 10.0.2.13
    public const ushort SCBotSuspectReportedPacket = 0x184;
    public const ushort SCBotSuspectArrestedPacket = 0x1CB; // 10.0.2.13
    public const ushort SCUnderWaterPacket = 0x1CD; // 10.0.2.13
    public const ushort SCCharacterGamePointsPacket = 0x1CE; // 10.0.2.13
    public const ushort SCGamePointChangedPacket = 0x1D0; // 10.0.2.13
    public const ushort SCJuryPointChangedPacket = 0x1D1; // 10.0.2.13
    public const ushort SCAppliedToInstantGamePacket = 0x1D2; // 10.0.2.13
    public const ushort SCCancelInstantGamePacket = 0x1D3; // 10.0.2.13
    public const ushort SCInstantGameStatePacket = 0x18d;
    public const ushort SCInviteToInstantGamePacket = 0x1D4; // 10.0.2.13
    public const ushort SCInstantGameInviteTimeoutPacket = 0x18f;
    public const ushort SCInstantGameJoinedPacket = 0x1D7; // 10.0.2.13
    public const ushort SCInstantGameStartPacket = 0x1DA; // 10.0.2.13
    public const ushort SCInstantGameEndPacket = 0x1DC; // 10.0.2.13
    public const ushort SCInstantGameAddPointPacket = 0x193;
    public const ushort SCInstantGameKillPacket = 0x1E2; // 10.0.2.13
    public const ushort SCInstantGameKillstreakPacket = 0x1E3; // 10.0.2.13
    public const ushort SCInstantGameUnkPacket = 0x196;
    public const ushort SCLoadInstancePacket = 0x1EA; // 10.0.2.13
    public const ushort SCProcessingInstancePacket = 0x1EB; // 10.0.2.13
    public const ushort SCGmCommandPacket = 0x1EF;  // 10.0.2.13
    public const ushort SCGmDumpInventoryPacket = 0x1F0; // 10.0.2.13
    public const ushort SCGmDumpEquipmentPacket = 0x1F1; // 10.0.2.13
    public const ushort SCGmDumpQuestsPacket = 0x19c;
    public const ushort SCGmDumpCompletedQuestsPacket = 0x1F3;  // 10.0.2.13
    public const ushort SCGmDumpNpcPacket = 0x1F4;  // 10.0.2.13
    public const ushort SCUnkPacket8 = 0x19f;
    public const ushort SCKickedPacket = 0x209; // 10.0.2.13
    public const ushort SCAccountWarnedPacket = 0x20A; // 10.0.2.13
    public const ushort SCAboxTeleportPacket = 0x20B; // 10.0.2.13
    public const ushort SCDelayedTaskOnInGameNotifyPacket = 0x20D; // 10.0.2.13
    public const ushort SCAppellationsPacket = 0x213; // 10.0.2.13
    public const ushort SCAppellationGainedPacket = 0x214; // 10.0.2.13
    public const ushort SCAppellationChangedPacket = 0x215; // 10.0.2.13
    public const ushort SCTutorialSavedPacket = 0x217; // 10.0.2.13
    public const ushort SCEmblemUploadedPacket = 0x218; // 10.0.2.13
    public const ushort SCEmblemDownloadedPacket = 0x219; // 10.0.2.13
    public const ushort SCShipyardStatePacket = 0x21A; // 10.0.2.13
    public const ushort SCSlaveStatePacket = 0x21B; // 10.0.2.13
    public const ushort SCMateStatePacket = 0x21C; // 10.0.2.13
    public const ushort SCDumpCombatInfoPacket = 0x21D;  // 10.0.2.13
    public const ushort SCUccCheckecPacket = 0x21E; // 10.0.2.13
    public const ushort SCShowQuestAreaPacket = 0x21F; // 10.0.2.13
    public const ushort SCShowCommonFarmPacket = 0x220; // 10.0.2.13
    public const ushort SCResponseCommonFarmListPacket = 0x221; // 10.0.2.13
    public const ushort SCTelescopeToggledPacket = 0x222; // 10.0.2.13
    public const ushort SCTelescopeUnitsPacket = 0x223; // 10.0.2.13
    public const ushort SCTransferTelescopeToggledPacket = 0x224; // 10.0.2.13
    public const ushort SCTransferTelescopeUnitsPacket = 0x225; // 10.0.2.13
    public const ushort SCSchoolOfFishFinderToggledPacket = 0x228; // 10.0.2.13
    public const ushort SCSchoolOfFishDoodadsPacket = 0x229; // 10.0.2.13
    public const ushort SCShowDemoModeUiPacket = 0x1b8;
    public const ushort SCDemoCharResetItemPacket = 0x1b9;
    public const ushort SCDemoCharResetLocPacket = 0x1ba;
    public const ushort SCDemoResetActionSlotPacket = 0x1bb;
    public const ushort SCSetBreathPacket = 0x22A; // 10.0.2.13
    public const ushort SCDoodadReqBattleFieldPacket = 0x1be;
    public const ushort SCCraftFailedPacket = 0x22D; // 10.0.2.13
    public const ushort SCExpertLimitModifiedPacket = 0x22E; // 10.0.2.13
    public const ushort SCExpertExpandedPacket = 0x22F; // 10.0.2.13
    public const ushort SCAccountInfoPacket = 0x230;
    public const ushort SCAiDebugPacket = 0x1c3;
    public const ushort SCAiAggroPacket = 0x23F; // 10.0.2.13
    public const ushort SCHSRequestPacket = 0x1c5;
    public const ushort SCHackGuardRetAddrsRequestPacket = 0x1c6;
    public const ushort SCUnitLocationPacket = 0x243; // 10.0.2.13
    public const ushort SCRestrictInfoPacket = 0x244; // 10.0.2.13
    public const ushort SCIsUnitInFarmPacket = 0x245; // 10.0.2.13
    public const ushort SCResponseUIDataPacket = 0x246; // 10.0.2.13
    public const ushort SCUnitVisualOptionsPacket = 0x247; // 10.0.2.13
    public const ushort SCNotifyUIMessagePacket = 0x249; // 10.0.2.13
    public const ushort SCResultRestrictCheckPacket = 0x24A;
    public const ushort SCICSMenuListPacket = 587;
    public const ushort SCICSGoodListPacket = 588;
    public const ushort SCICSGoodDetailPacket = 589;
    public const ushort SCICSCheckTimePacket = 590;
    public const ushort SCICSBuySucceededPacket = 591;
    public const ushort SCICSBuyFailedPacket = 592;
    public const ushort SCICSSyncGoodPacket = 593;
    public const ushort SCICSCashPointPacket = 594;
    public const ushort SCICSExchangeRatioPacket = 595;
    public const ushort SCICSBuyCountPacket = 596;
    public const ushort SCICSResetDailyPurchaseLimitPacket = 597;
    public const ushort SCPremiumServiceListPacket = 0x256; // 10.0.2.13
    public const ushort SCBountyListPacket = 0x1d9;
    public const ushort SCSetBountyPermittedPacket = 0x1da;
    public const ushort SCSetBountyDonePacket = 0x1db;
    public const ushort SCBountyPaidPacket = 0x1dc;
    public const ushort SCInvitationCanceledPacket = 0x257; // 10.0.2.13
    public const ushort SCPlaySoundPacket = 0x258; // 10.0.2.13
    public const ushort SCSendUserMusicPacket = 0x259; // 10.0.2.13
    public const ushort SCUserNoteLoadedPacket = 0x25A; // 10.0.2.13
    public const ushort SCPauseUserMusicPacket = 0x25B; // 10.0.2.13
    public const ushort SCGetSlotCountPacket = 0x264;
    public const ushort SCSecondPassSettedPacket = 0x265; // 10.0.2.13
    public const ushort SCSecondPassKeyTablesPacket = 0x266; // 10.0.2.13
    public const ushort SCSecondPassChangedPacket = 0x267; // 10.0.2.13
    public const ushort SCSecondPassCheckedPacket = 0x268; // 10.0.2.13
    public const ushort SCSecondPassClearedPacket = 0x269; // 10.0.2.13
    public const ushort SCSecondPassCheckOverFailedPacket = 0x26A; // 10.0.2.13
    public const ushort SCSecondPassAccountLockedPacket = 0x26B; // 10.0.2.13
    public const ushort SCSecondPassCreatedPacket = 0x26C; // 10.0.2.13
    public const ushort SCScheduleItemUpdatePacket = 0x26E; // 10.0.2.13
    public const ushort SCScheduledEventStartedPacket = 0x26F; // 10.0.2.13
    public const ushort SCScheduledEventEndedPacket = 0x270; // 10.0.2.13
    public const ushort SCMouldListPacket = 0x1ee;
    public const ushort SCMouldAskedPacket = 0x1ef;
    public const ushort SCMouldTakenPacket = 0x1f0;
    public const ushort SCToggleBeautyshopResponsePacket = 0x271; // 10.0.2.13
    public const ushort SCCharacterGenderAndModelModifiedPacket = 0x272; // 10.0.2.13
    public const ushort SCSpecialtyCurrentPacket = 0x278; // 10.0.2.13
    public const ushort SCUnitIdleStatusPacket = 0x279; // 10.0.2.13
    public const ushort SCRaceCondPacket = 0x1f6;
    public const ushort SCRacingPacket = 0x1f7;
    public const ushort SCRacingResultPacket = 0x1f8;
    public const ushort SCRankRewardMailPacket = 0x27D; // 10.0.2.13
    public const ushort SCRankCharacterPacket = 0x1fa; // 10.0.2.13
    public const ushort SCAchievementsPacket = 0x27F; // 10.0.2.13
    public const ushort SCAchievementChangedPacket = 0x280; // 10.0.2.13
    public const ushort SCAchievementCompletedPacket = 0x281; // 10.0.2.13
    public const ushort SCAchievementResetedPacket = 0x282; // 10.0.2.13
    public const ushort SCAchievementItemSentPacket = 0x283; // 10.0.2.13
    public const ushort SCUpdatePremiumPointPacket = 0x288; // 10.0.2.13
    public const ushort SCPremiumPointChangedPacket = 0x289; // 10.0.2.13
    public const ushort SCUnitGmModeChangedPacket = 0x28A; // 10.0.2.13
    public const ushort SCUnitPvPPointsChangedPacket = 0x28B; // 10.0.2.13
    public const ushort SCRankAlarmPacket = 0x27E; // 10.0.2.13
    public const ushort SCUnkPacket15 = 0x206; // Select Dimension, uint ZoneGroupId
    public const ushort SCUnkPacket16 = 0x207;
    public const ushort SCUnkPacket17 = 0x208; // Secure mode error message
    public const ushort SCUnkCharacterAddStatPacket = 0x209;
    public const ushort SCUnlockCurrencySlotPacket = 0x28F; // 10.0.2.13
    public const ushort SCUnkPacket20 = 0x20b;
    public const ushort SCUnkPacket21 = 0x20c;
    public const ushort SCUnkPacket22 = 0x20d;
    public const ushort SCUnkPacket23 = 0x20e;
    public const ushort SCUnkPacket24 = 0x20f;
    public const ushort SCUnkPacket28 = 0x210;
    public const ushort SCWorldMessagePacket = 0x299; // 10.0.2.13
    public const ushort SCUnkPacket25 = 0x212;
    public const ushort SCUnkPacket26 = 0x213;
    public const ushort SCUnkPacket27 = 0x214;
    public const ushort SCAccountAttributeListPacket = 0x29D;
    public const ushort SCAccountAttributeConfigPacket = 0x2A0;
    public const ushort SCIdleKickPacket = 0x2A1; // 10.0.2.13
    public const ushort SCWorldRestrictOwnerChangePacket = 0x2A2; // 10.0.2.13 SC_PACKET_WORLD_RESTRICT_OWNER_CHANGE (674)
    public const ushort SCLevelRestrictionConfigPacket = 0x2A3;
    public const ushort SCTaxItemConfigPacket = 0x2A4; // 10.0.2.13 SC_PACKET_TAX_ITEM_CONFIG (676)
    public const ushort SCInGameShopConfigPacket = 0x2BB; // 10.0.2.13 SC_PACKET_INGAME_SHOP_CONFIG (699)
    public const ushort SCGameRuleConfigPacket = 0x2BC; // 10.0.2.13 SC_PACKET_GAME_RULE_CONFIG (700)
    public const ushort SCHousingAreaConfigPacket = 0x2BD; // 10.0.2.13 SC_PACKET_HOUSING_AREA_CONFIG (701)
    public const ushort SCSiegeZoneConfigPacket = 0x2BE; // 10.0.2.13 SC_PACKET_SIEGE_ZONE_CONFIG (702)
    public const ushort SCShowCurrentWorldPacket = 0x354; // 10.0.2.13 SC_PACKET_SHOW_CURRENT_WORLD (852)
    public const ushort SCWorldContentPacket = 0x009; // 10.0.2.13 SC_PACKET_WORLD_CONTENT (9)
    public const ushort SCServerFileTimeSyncPacket = 0x305; // 10.0.2.13 SC_PACKET_SERVER_FILE_TIME_SYNC (773)
    public const ushort SCRepreSentCharacterPacket = 0x2C4; // 10.0.2.13 SC_PACKET_REPRESENT_CHARACTER (708)
    public const ushort SCAccountAttendancePacket = 0x2C9; // 10.0.2.13 SC_PACKET_ACCOUNT_ATTENDANCE (713)
    public const ushort SCServerInfoPacket = 0x399; // 10.0.2.13 SC_PACKET_SERVER_INFO (921)
    public const ushort SCUnitOpenEquipInfoPacket = 0x248;
    public const ushort SCSpawnedMonitorNpcsPacket = 0x2D6;
    public const ushort SCMonitorNpcSpawnedPacket = 0x2D7;
    public const ushort SCEventInfoCountPacket = 0x2DD; // 10.0.2.13 SC_PACKET_EVENT_INFO_COUNT (733)
    public const ushort SCFactionPowerScorePacket = 0x00C; // 10.0.2.13 SC_PACKET_FACTION_POWER_SCORE (12)
    public const ushort SCIncreasedFavoritePortalLimitPacket = 0x08D; // 10.0.2.13 SC_PACKET_INCREASED_FAVORITE_PORTAL_LIMIT (141)
    public const ushort SCInstanceVisitCountsPacket = 0x1EC; // 10.0.2.13 SC_PACKET_INSTANCE_VISIT_COUNTS (492)
    public const ushort SCFavoriteCraftsPacket = 0x23A; // 10.0.2.13 SC_PACKET_FAVORITE_CRAFTS (570)
    public const ushort SCBattleFieldRecordsPacket = 0x2E5; // 10.0.2.13 SC_PACKET_BATTLE_FIELD_RECORDS (741)
    public const ushort SCCharacterPrivacyStatusUpdatePacket = 0x375; // 10.0.2.13 SC_PACKET_CHARACTER_PRIVACY_STATUS_UPDATE (885)
    public const ushort SCUpdateAdditionalSkillPointPacket = 0x381; // 10.0.2.13 SC_PACKET_UPDATE_ADDITIONAL_SKILL_POINT (897)
    public const ushort SCPlayerGameDataPacket = 0x39A; // 10.0.2.13 SC_PACKET_PLAYER_GAME_DATA (922)
    public const ushort SCCharacterPrelimEquipmentsPacket = 0x79; // 10.0.2.13 SC_PACKET_CHARACTER_PRELIM_EQUIPMENTS (121)
    public const ushort SCSystemFeatureStateListPacket = 0x393; // 10.0.2.13 SC_PACKET_SYSTEM_FEATURE_STATE_LIST (915)
    public const ushort SCWorldLevelInfoPacket = 0x38A; // 10.0.2.13 SC_PACKET_WORLD_LEVEL_INFO (906)

    // Ids for packet types the 10.0.2.13 client declares that this file did not. Recovered
    public const ushort SCAbilitySetSlotCountUpdatedPacket = 0x14B;
    public const ushort SCAbilitySetUpdatedPacket = 0x14A;
    public const ushort SCAboxBlessUthstinApplyStatsPacket = 0x2F1;
    public const ushort SCAccountAttendanceAddedPacket = 0x2CA;
    public const ushort SCAccountAttendanceRewardedPacket = 0x2CC;
    public const ushort SCAccountAttributeRemovedPacket = 0x29F;
    public const ushort SCUpdateSkillActiveTypePacket = 0x2E0;
    public const ushort SCListSkillActiveTypePacket = 0x2E1;
    public const ushort SCHeirSkillListPacket = 0x2F4;
    public const ushort SCActivatedHeirSkillPacket = 0x2F5;
    public const ushort SCResetHeirSkillPacket = 0x2F6;
    public const ushort SCHeirLevelUpPacket = 0x2F3;
    public const ushort SCAddContributionPointPacket = 0x27;
    public const ushort SCAppellationStampLifespanExpiredPacket = 0x383;
    public const ushort SCAppellationStampLifespanUpdatedPacket = 0x384;
    public const ushort SCArchePassChangeMissionPacket = 0x342;
    public const ushort SCArchePassMissionCountPacket = 0x341;
    public const ushort SCAttackFactionPacket = 0x327;
    public const ushort SCBalanceLevelChangedPacket = 0x141;
    public const ushort SCBattleFieldBestRatingRewardPacket = 0x2E7;
    public const ushort SCBlessUthstinApplyStatsPacket = 0x2ED;
    public const ushort SCBlessUthstinConsumeApplyStatsPacket = 0x2EC;
    public const ushort SCBlessUthstinCopyPagePacket = 0x2F0;
    public const ushort SCBlessUthstinExpandPagePacket = 0x2EE;
    public const ushort SCBlessUthstinExtendMaxStatsPacket = 0x2EB;
    public const ushort SCBlessUthstinInitStatsPacket = 0x2EA;
    public const ushort SCBlessUthstinSelectPagePacket = 0x2EF;
    public const ushort SCBlockInstanceNotifyPacket = 0x210;
    public const ushort SCBlockItemSellFaileMessagePacket = 0x36F;
    public const ushort SCBossTelescopeToggledPacket = 0x226;
    public const ushort SCButlerDespawnedPacket = 0x349;
    public const ushort SCButlerLookChangedPacket = 0x34D;
    public const ushort SCButlerSpawnedPacket = 0x347;
    public const ushort SCChangeAbilitySetPassiveBuffPacket = 0x14C;
    public const ushort SCChangeSquadMemberRatingPacket = 0x31C;
    public const ushort SCChargeSkillCooldownChangedPacket = 0x31D;
    public const ushort SCChronicleInfoDeletePacket = 0x356;
    public const ushort SCChronicleInfoUpdatePacket = 0x358;
    public const ushort SCCompletedArchePassPacket = 0x340;
    public const ushort SCConnectStateMemberPacket = 0x310;
    public const ushort SCCraftOrderActionResultPacket = 0x235;
    public const ushort SCCraftOrderFeeInfoPacket = 0x236;
    public const ushort SCDeclarationFailureReasonPacket = 0x21;
    public const ushort SCDelegateSquadLeaderPacket = 0x315;
    public const ushort SCDeleteCraftOrderEntryPacket = 0x233;
    public const ushort SCDeleteExpeditionPortalPacket = 0x372;
    public const ushort SCDominionNonPvPStartedPacket = 0x36;
    public const ushort SCDominionNonPvPStoppedPacket = 0x37;
    public const ushort SCDominionTaxChangedPacket = 0x35;
    public const ushort SCDoodadFirstInteractionSyncPacket = 0x306;
    public const ushort SCDoodadHitPacket = 0x19F;
    public const ushort SCDoodadInteractionCallbackPacket = 0x157;
    public const ushort SCSetDoodadManikinSkinPacket = 0x158; // 10.0.2.13
    public const ushort SCDoodadMapIconRemovedPacket = 0x322;
    public const ushort SCDoodadWorldmapTextAddedPacket = 0x324;
    public const ushort SCDoodadWorldmapTextRemovedPacket = 0x325;
    public const ushort SCDropQuestsByFactionChangePacket = 0x343;
    public const ushort SCDumpGachaRecordPacket = 0x2E4;
    public const ushort SCElectSiegeRaidOwnerPacket = 0x32F;
    public const ushort SCEnsembleMidiBinReadyPacket = 0x25F;
    public const ushort SCExpdWarHistoriesPacket = 0x1E;
    public const ushort SCExpeditionApplicantAcceptPacket = 0x45;
    public const ushort SCExpeditionApplicantAddPacket = 0x43;
    public const ushort SCExpeditionApplicantDelPacket = 0x44;
    public const ushort SCExpeditionApplicantRejectPacket = 0x46;
    public const ushort SCExpeditionBuffChangedPacket = 0x4E;
    public const ushort SCExpeditionCreatedPacket = 0x015; // 10.0.2.13
    public const ushort SCExpeditionExpAddPacket = 0x4C;
    public const ushort SCExpeditionMemberListEndPacket = 0x24;
    public const ushort SCExpeditionPortalTimerPacket = 0x373;
    public const ushort SCExpeditionRejoinFailPacket = 0x68;
    public const ushort SCExpeditionShopHistoriesPacket = 0x01C; // 10.0.2.13
    public const ushort SCExpeditionSummonSuggestPacket = 0x4A;
    public const ushort SCExpeditionWarStatePacket = 0x78;
    public const ushort SCFactionCompetitionUpdatePointPacket = 0x338;
    public const ushort SCFactionImmigrateLimitDataPacket = 0x51;
    public const ushort SCFactionMobilizationOrderPacket = 0x3D;
    public const ushort SCFactionRelationRequestPacket = 0x2B;
    public const ushort SCFactionRelationResponsePacket = 0x2C;
    public const ushort SCFamilyChangeMemberLevelPacket = 0x5E;
    public const ushort SCFamilyChangeMemberRolePacket = 0x5D;
    public const ushort SCFamilyExpChangeDryNotifyPacket = 0x61;
    public const ushort SCFamilyExpChangeNotifyPacket = 0x060; // 10.0.2.13
    public const ushort SCFamilyInfoSetPacket = 0x5F;
    public const ushort SCFestivalZoneStatePacket = 0x12F;
    public const ushort SCFollowAskPacket = 0x9B;
    public const ushort SCFollowRespPacket = 0x9C;
    public const ushort SCFriendRequestPacket = 0x379;
    public const ushort SCFriendAcceptPacket = 0x37A;
    public const ushort SCFriendCancelPacket = 0x37B;
    public const ushort SCGamePointInitedPacket = 0x1CF;
    public const ushort SCGameScheduleControlPacket = 0x276;
    public const ushort SCGmDumpItemGradeEnchantRatioPacket = 0x1F5;
    public const ushort SCGmDumpSkillsPacket = 0x1FD;
    public const ushort SCGmUseWithTargetPacket = 0x20C;
    public const ushort SCHGRequestPacket = 0x3B;
    public const ushort SCHeroBindFactionRezDistrictInfoPacket = 0x2B9;
    public const ushort SCHeroCandidateNotificationPacket = 0x2AD;
    public const ushort SCHeroDominionPointCountPacket = 0x2B7;
    public const ushort SCHeroElectionMailPacket = 0x2B1;
    public const ushort SCHeroGiveDominionPointPacket = 0x2B6;
    public const ushort SCHeroInfoDeletedPacket = 0x2B2;
    public const ushort SCHeroScoreUpdatedPacket = 0x2AA;
    public const ushort SCHeroSeasonInfoPacket = 0x2A8;
    public const ushort SCHeroSeasonOffPacket = 0x2A9;
    public const ushort SCHeroVotingPacket = 0x2AF;
    public const ushort SCHouseRotatedPacket = 0xFE;
    public const ushort SCHousingDecoLimitExpandedPacket = 0xFF;
    public const ushort SCIgnoreMinimumGameSizeNotifyPacket = 0x20E;
    public const ushort SCIndunDirectTelPacket = 0x29A;
    public const ushort SCIndunInitialRoundInfoPacket = 0x2D9;
    public const ushort SCIndunPortalSpawnPacket = 0x29C;
    public const ushort SCIndunRoundPlayStatusPacket = 0x2DB;
    public const ushort SCInstantGameCountDownPacket = 0x1D8;
    public const ushort SCInstantGameKillstreakResetPacket = 0x1E4;
    public const ushort SCInstantGameReentryNotifyPacket = 0x1E8;
    public const ushort SCInstantGameStartPointReturnTimePacket = 0x1E6;
    public const ushort SCInstantGameUnearnedWinPacket = 0x1E5;
    public const ushort SCInstantGameUpdateTimePacket = 0x1DB;
    public const ushort SCInstantTimePacket = 0x2E8;
    public const ushort SCIntegrationDummyFactionPacket = 0x352;
    public const ushort SCInvitationAnswerPacket = 0x1D5;
    public const ushort SCItemElementResultPacket = 0x359;
    public const ushort SCItemEnchantMagicalResultPacket = 0xCB;
    public const ushort SCItemSmeltingResultPacket = 0xCF;
    public const ushort SCItemSocketingResultPacket = 0xCA;
    // 10.0.2.13, read out of the client's server-to-client handler table: the slot for opcode N sits
    // at table+8+N*8 and its "registered" flag at table+0x1ce0+N. Verified against the entries that
    // were already known here (0xC9, 0xCA, 0xCF, 0xD0, 0x359 all resolve to the same values).
    public const ushort SCItemRefurbishmentResultPacket = 0xCC; // Tempering
    public const ushort SCItemEvolvingResultPacket = 0xCD; // Synthesis
    public const ushort SCItemReRollEvolvingResultPacket = 0xCE; // Synthesis, effect swap
    public const ushort SCScaleEnchantBroadcastPacket = 0xD1; // Tempering, server-wide notice
    public const ushort SCRestoreDisableEnchantPacket = 0xD3;
    public const ushort SCItemChangeMappingResultPacket = 0xD4; // Awakening
    public const ushort SCLoadCraftOrderEntryPacket = 0x231;
    public const ushort SCMailRemovedFromAboxPacket = 0x168;
    public const ushort SCMatchingInvitationInfoPacket = 0x1D6;
    public const ushort SCMateEquipmentFlagsChangedPacket = 0x16D;
    public const ushort SCNewDayStartPacket = 0x2CB;
    public const ushort SCNotifySquadEventPacket = 0x316;
    public const ushort SCNuonsArrowMsgPacket = 0x19E;
    public const ushort SCPassportIssuedPacket = 0x2F8;
    public const ushort SCPirateMemberLimitCountPacket = 0x32A;
    public const ushort SCPlotAuctionBidResponsePacket = 0x395;
    public const ushort SCPlotAuctionBidUpdatePacket = 0x397;
    public const ushort SCPremiumBonusListPacket = 0x2D1;
    public const ushort SCProtectSensitiveOperationResultPacket = 0x28E;
    public const ushort SCUpdatedSlaveSourceItemPacket = 0x296;
    public const ushort SCQuestAcceptConditionalPacket = 0x18F;
    public const ushort SCQuestNotifierInitPacket = 0x287;
    public const ushort SCRaidApplicantAcceptPacket = 0x301;
    public const ushort SCRaidApplicantDelPacket = 0x300;
    public const ushort SCRaidApplicantRejectPacket = 0x302;
    public const ushort SCRaidRecruitDelPacket = 0x2FB;
    public const ushort SCRaidRecruitDetailPacket = 0x2FE;
    public const ushort SCRaidRecruitOptionPacket = 0x2FD;
    public const ushort SCRandomShopBaseInfoUpdatePacket = 0x36B;
    public const ushort SCRandomShopInfoResetPacket = 0x369;
    public const ushort SCReopenRandomBoxRemovePacket = 0x388;
    public const ushort SCReportBadwordUserPacket = 0x2D0;
    public const ushort SCReputationChangedPacket = 0x2A5;
    public const ushort SCUpdateMerchantGoodLimitPurchasePacket = 0x376;
    public const ushort SCBuyFailedMerchantGoodLimitPurchasePacket = 0x377;
    public const ushort SCResetMerchantGoodLimitPurchasePacket = 0x378;
    public const ushort SCResidentBalanceInfoPacket = 0x3A;
    public const ushort SCResidentInfoPacket = 0x39;
    public const ushort SCReturnAccountStatusPacket = 0x334;
    public const ushort SCRotateHousePacket = 0x9A;
    public const ushort SCSailingActivityEnterResponsePacket = 0x390;
    public const ushort SCSailingActivityErrorPacket = 0x38F;
    public const ushort SCSailingActivityPointsChangedPacket = 0x392;
    public const ushort SCSecondPassReservedClearTimePacket = 0x26D;
    public const ushort SCSelectedInstanceDifficultPacket = 0x2DC;
    public const ushort SCSetExpeditionProtectDatePacket = 0x22;
    public const ushort SCSiegeScorePointPacket = 0x33C;
    public const ushort SCSkillCooldownReducePacket = 0x304;
    public const ushort SCSlaveEquipmentExpiredPacket = 0x94;
    public const ushort SCSlaveEquipmentFlagsChangedPacket = 0x96;
    public const ushort SCSnowingEverywherePacket = 0xE9;
    public const ushort SCSquadSetGameInfoPacket = 0x31A;
    public const ushort SCStoreTradeFailedPacket = 0x290;
    public const ushort SCSuspectGoingBotTrialPacket = 0x1CC;
    public const ushort SCSysIndunIndexPacket = 0x28D;
    public const ushort SCTeamJointBreakPacket = 0x122;
    public const ushort SCTeamOfficerChangedPacket = 0x32D;
    public const ushort SCTeamSummonSuggestPacket = 0x125;
    public const ushort SCTodayAssignmentChangedPacket = 0x285;
    public const ushort SCTodayAssignmentGoalPacket = 0x286;
    public const ushort SCTodayAssignmentItemSentPacket = 0x284;
    public const ushort SCTodayAssignmentResetCountPacket = 0x328;
    public const ushort SCTodayAssignmentAcceptAllPacket = 0x329;
    public const ushort SCUlcNeedSquadNoticePacket = 0x31E;
    public const ushort SCUnitCollisionResultPacket = 0x18A;
    public const ushort SCUnlockLearnSkillPacket = 0x146;
    public const ushort SCUpdateHousingUccPacket = 0x326;
    public const ushort SCUpdatedFavoriteCraftsPacket = 0x23B;
    public const ushort SCZoneScoreResetPacket = 0x351;
    public const ushort SCZoneScoreUpdatePacket = 0x350;
    public const ushort SCRankSnapshotPacket = 0x27A; // 10.0.2.13
    public const ushort SCRankRewardSnapshotPacket = 0x27B;
    public const ushort SCGmDumpAchievementPacket = 0x1F9; // 10.0.2.13
    public const ushort SCGmDumpAppellationPacket = 0x20;
    public const ushort SCGmDumpBuycodePacket = 0x203;
    public const ushort SCGmDumpDailyResetPacket = 0x201;
    public const ushort SCGmDumpGamePointPacket = 0x1FA;
    public const ushort SCGmDumpGuidActionSlotPacket = 0x202;
    public const ushort SCGmDumpRecordPacket = 0x1FB; // 10.0.2.13
    public const ushort SCGmDumpRestrictPacket = 0x1FC;
    public const ushort SCGmDumpReturnDistrictPacket = 0x200; // 10.0.2.13
    public const ushort SCGmDumpSubStatPacket = 0x250;
    public const ushort SCGmServerAttributeValuePacket = 0x366;

    public const ushort SCCombatResourcePointPacket = 0x35B;

    public const ushort SCSkillMapEffectPacket = 0x32B;

    public const ushort SCAccountAttributeUpdatedPacket = 0x29E;
}
