using AAEmu.Game.Models.Game.Skills.Static;

namespace AAEmu.UnitTests.Game.Models.Game.Skills.Static;

/// <summary>
/// Every case of the client's result-to-symbol switch: the wire byte, the symbol
/// the client returns for it and the SkillResult member that owns it.
/// The UI shows ui_texts key "skill_" + lower(symbol) (category 89). Bytes absent here fall to the switch
/// default, "URK_UNKNOWN".
/// </summary>
public static class SkillResultClientTable
{
    public sealed record Row(byte Wire, string Symbol, SkillResult Member);

    public static readonly IReadOnlyList<Row> Rows =
    [
        new(0x00, "SUCCESS", SkillResult.Success),
        new(0x01, "FAILURE", SkillResult.Failure),
        new(0x02, "SOURCE_DIED", SkillResult.SourceDied),
        new(0x03, "SOURCE_ALIVE", SkillResult.SourceAlive),
        new(0x04, "TARGET_DIED", SkillResult.TargetDied),
        new(0x05, "TARGET_DESTROYED", SkillResult.TargetDestroyed),
        new(0x06, "TARGET_ALIVE", SkillResult.TargetAlive),
        new(0x07, "ON_CASTING", SkillResult.OnCasting),
        new(0x08, "COOLDOWN_TIME", SkillResult.CooldownTime),
        new(0x09, "NO_TARGET", SkillResult.NoTarget),
        new(0x0A, "LACK_HEALTH", SkillResult.LackHealth),
        new(0x0B, "LACK_MANA", SkillResult.LackMana),
        new(0x0C, "OBSTACLE", SkillResult.Obstacle),
        new(0x0D, "OUTOF_HEIGHT", SkillResult.OutofHeight),
        new(0x0E, "TOO_CLOSE_RANGE", SkillResult.TooCloseRange),
        new(0x0F, "TOO_FAR_RANGE", SkillResult.TooFarRange),
        new(0x10, "OUTOF_ANGLE", SkillResult.OutofAngle),
        new(0x11, "CANNOT_CAST_IN_COMBAT", SkillResult.CannotCastInCombat),
        new(0x12, "CANNOT_CAST_WHILE_MOVING", SkillResult.CannotCastWhileMoving),
        new(0x13, "CANNOT_CAST_IN_STUN", SkillResult.CannotCastInStun),
        new(0x14, "CANNOT_CAST_WHILE_WALKING", SkillResult.CannotCastWhileWalking),
        new(0x15, "CANNOT_CAST_IN_SWIMMING", SkillResult.CannotCastInSwimming),
        new(0x16, "BLANK_MINDED", SkillResult.BlankMinded),
        new(0x17, "SILENCE", SkillResult.Silence),
        new(0x18, "CRIPPLED", SkillResult.Crippled),
        new(0x19, "CANNOT_CAST_IN_CHANNELING", SkillResult.CannotCastInChanneling),
        new(0x1A, "CANNOT_CAST_IN_PRISON", SkillResult.CannotCastInPrison),
        new(0x1B, "NEED_STEALTH", SkillResult.NeedStealth),
        new(0x1C, "NEED_NOCOMBAT_TARGET", SkillResult.NeedNocombatTarget),
        new(0x1D, "TARGET_IMMUNE", SkillResult.TargetImmune),
        new(0x1E, "INVALID_SKILL", SkillResult.InvalidSkill),
        new(0x1F, "INACTIVE_ABILITY", SkillResult.InactiveAbility),
        new(0x20, "NOT_ENOUGH_ABILITY_LEVEL", SkillResult.NotEnoughAbilityLevel),
        new(0x21, "INVALID_SOURCE", SkillResult.InvalidSource),
        new(0x22, "INVALID_TARGET", SkillResult.InvalidTarget),
        new(0x23, "INVALID_LOCATION", SkillResult.InvalidLocation),
        new(0x24, "NEED_REAGENT", SkillResult.NeedReagent),
        new(0x25, "ITEM_LOCKED", SkillResult.ItemLocked),
        new(0x26, "NEED_MONEY", SkillResult.NeedMoney),
        new(0x27, "NEED_LABOR_POWER", SkillResult.NeedLaborPower),
        new(0x28, "SOURCE_IS_HANGING", SkillResult.SourceIsHanging),
        new(0x29, "SOURCE_IS_RIDING", SkillResult.SourceIsRiding),
        new(0x2A, "HIGHER_BUFF", SkillResult.HigherBuff),
        new(0x2B, "NOT_PVP_AREA", SkillResult.NotPvpArea),
        new(0x2C, "NOT_NOW", SkillResult.NotNow),
        new(0x2D, "NO_PERM", SkillResult.NoPerm),
        new(0x2E, "BAG_FULL", SkillResult.BagFull),
        new(0x2F, "PROTECTED_FACTION", SkillResult.ProtectedFaction),
        new(0x30, "PROTECTED_LEVEL", SkillResult.ProtectedLevel),
        new(0x31, "UNIT_REQS_OR_FAIL", SkillResult.UnitReqsOrFail),
        new(0x32, "SKILL_REQ_FAIL", SkillResult.SkillReqFail),
        new(0x33, "BACKPACK_OCCUPIED", SkillResult.BackpackOccupied),
        new(0x34, "OBSTACLE_FOR_SPAWN_DOODAD", SkillResult.ObstacleForSpawnDoodad),
        new(0x35, "CANNOT_SPAWN_DOODAD_IN_HOUSE", SkillResult.CannotSpawnDoodadInHouse),
        new(0x36, "CANNOT_USE_FOR_SELF", SkillResult.CannotUseForSelf),
        new(0x37, "NOT_PREOCCUPIED", SkillResult.NotPreoccupied),
        new(0x38, "NOT_MY_NPC", SkillResult.NotMyNpc),
        new(0x39, "NOT_CHECKED_SECOND_PASS", SkillResult.NotCheckedSecondPass),
        new(0x3A, "ZONE_BANNED", SkillResult.ZoneBanned),
        new(0x3B, "INVALID_GRADE_ENCHANT_SUPPORT_ITEM", SkillResult.InvalidGradeEnchantSupportItem),
        new(0x3C, "ITEM_SECURED", SkillResult.ItemSecured),
        new(0x3D, "INVALID_ACCOUNT_ATTRIBUTE", SkillResult.InvalidAccountAttribute),
        new(0x3E, "FESTIVAL_ZONE", SkillResult.FestivalZone),
        new(0x3F, "ALREADY_OTHER_PLAYER_BOUND", SkillResult.AlreadyOtherPlayerBound),
        new(0x41, "CANNOT_UNSUMMON_UNDER_STUN_SLEEP_ROOT", SkillResult.CannotUnsummonUnderStunSleepRoot),
        new(0x42, "LACK_COMBAT_RESOURCE", SkillResult.LackCombatResource),
        new(0x43, "LACK_SOURCE_ITEM_SET", SkillResult.LackSourceItemSet),
        new(0x44, "LACK_ACTABILITY", SkillResult.LackActability),
        new(0x45, "ONLY_DURING_SWIMMING", SkillResult.OnlyDuringSwimming),
        new(0x46, "ULC_ALREADY_ACTIVATED", SkillResult.UlcAlreadyActivated),
        new(0x47, "HOUSE_OWNER", SkillResult.HouseOwner),
        new(0x48, "SOURCE_CANNOT_USE_WHILE_JUMPING", SkillResult.SourceCannotUseWhileJumping),
        new(0x49, "SOURCE_CANNOT_USE_WHILE_LEVITATING", SkillResult.SourceCannotUseWhileLevitating),
        new(0x4A, "URK_LEVEL", SkillResult.UrkLevel),
        new(0x4B, "URK_ABILITY", SkillResult.UrkAbility),
        new(0x4C, "URK_RACE", SkillResult.UrkRace),
        new(0x4D, "URK_GENDER", SkillResult.UrkGender),
        new(0x4E, "URK_EQUIP_SLOT", SkillResult.UrkEquipSlot),
        new(0x4F, "URK_EQUIP_ITEM", SkillResult.UrkEquipItem),
        new(0x50, "URK_OWN_ITEM", SkillResult.UrkOwnItem),
        new(0x51, "URK_TRAINED_SKILL", SkillResult.UrkTrainedSkill),
        new(0x52, "URK_COMBAT", SkillResult.UrkCombat),
        new(0x53, "URK_STEALTH", SkillResult.UrkStealth),
        new(0x54, "URK_HEALTH", SkillResult.UrkHealth),
        new(0x55, "URK_BUFF", SkillResult.UrkBuff),
        new(0x56, "URK_TARGET_BUFF", SkillResult.UrkTargetBuff),
        new(0x57, "URK_TARGET_COMBAT", SkillResult.UrkTargetCombat),
        new(0x58, "URK_CAN_LEARN_CRAFT", SkillResult.UrkCanLearnCraft),
        new(0x59, "URK_DOODAD_RANGE", SkillResult.UrkDoodadRange),
        new(0x5A, "URK_EQUIP_SHIELD", SkillResult.UrkEquipShield),
        new(0x5B, "URK_NOBUFF", SkillResult.UrkNobuff),
        new(0x5C, "URK_TARGET_BUFF_TAG", SkillResult.UrkTargetBuffTag),
        new(0x5D, "URK_CORPSE_RANGE", SkillResult.UrkCorpseRange),
        new(0x5E, "URK_EQUIP_WEAPON_TYPE", SkillResult.UrkEquipWeaponType),
        new(0x5F, "URK_TARGET_HEALTH_LESS_THAN", SkillResult.UrkTargetHealthLessThan),
        new(0x60, "URK_TARGET_NPC", SkillResult.UrkTargetNpc),
        new(0x61, "URK_TARGET_DOODAD", SkillResult.UrkTargetDoodad),
        new(0x62, "URK_EQUIP_RANGED", SkillResult.UrkEquipRanged),
        new(0x63, "URK_NO_BUFF_TAG", SkillResult.UrkNoBuffTag),
        new(0x64, "URK_COMPLETE_QUEST_CONTEXT", SkillResult.UrkCompleteQuestContext),
        new(0x65, "URK_PROGRESS_QUEST_CONTEXT", SkillResult.UrkProgressQuestContext),
        new(0x66, "URK_READY_QUEST_CONTEXT", SkillResult.UrkReadyQuestContext),
        new(0x67, "URK_TARGET_NPC_GROUP", SkillResult.UrkTargetNpcGroup),
        new(0x68, "URK_AREA_SPHERE", SkillResult.UrkAreaSphere),
        new(0x69, "URK_EXCEPT_COMPLETE_QUEST_CONTEXT", SkillResult.UrkExceptCompleteQuestContext),
        new(0x6A, "URK_PRECOMPLETE_QUEST_CONTEXT", SkillResult.UrkPrecompleteQuestContext),
        new(0x6B, "URK_TARGET_OWNER_TYPE", SkillResult.UrkTargetOwnerType),
        new(0x6C, "URK_NOT_UNDER_WATER", SkillResult.UrkNotUnderWater),
        new(0x6D, "URK_FACTION_MATCH", SkillResult.UrkFactionMatch),
        new(0x6E, "URK_TOD", SkillResult.UrkTod),
        new(0x6F, "URK_MOTHER_FACTION", SkillResult.UrkMotherFaction),
        new(0x70, "URK_ACTABILITY_POINT", SkillResult.UrkActabilityPoint),
        new(0x71, "URK_CRIME_POINT", SkillResult.UrkCrimePoint),
        new(0x72, "URK_HONOR_POINT", SkillResult.UrkHonorPoint),
        new(0x73, "URK_LIVING_POINT", SkillResult.UrkLivingPoint),
        new(0x74, "URK_CRIME_RECORD", SkillResult.UrkCrimeRecord),
        new(0x75, "URK_JURY_POINT", SkillResult.UrkJuryPoint),
        new(0x76, "URK_SOURCE_OWNER_TYPE", SkillResult.UrkSourceOwnerType),
        new(0x77, "URK_APPELLATION", SkillResult.UrkAppellation),
        new(0x78, "URK_IN_ZONE", SkillResult.UrkInZone),
        new(0x79, "URK_OUT_ZONE", SkillResult.UrkOutZone),
        new(0x7A, "URK_VERDICT_ONLY", SkillResult.UrkVerdictOnly),
        new(0x7B, "URK_FACTION_MATCH_ONLY", SkillResult.UrkFactionMatchOnly),
        new(0x7C, "URK_MOTHER_FACTION_ONLY", SkillResult.UrkMotherFactionOnly),
        new(0x7D, "URK_FACTION_MATCH_ONLY_NOT", SkillResult.UrkFactionMatchOnlyNot),
        new(0x7E, "URK_MOTHER_FACTION_ONLY_NOT", SkillResult.UrkMotherFactionOnlyNot),
        new(0x7F, "URK_NATION_MEMBER", SkillResult.UrkNationMember),
        new(0x80, "URK_NATION_MEMBER_NOT", SkillResult.UrkNationMemberNot),
        new(0x81, "URK_DOMINION_MEMBER_AT_POS", SkillResult.UrkDominionMemberAtPos),
        new(0x82, "URK_DOMINION_MEMBER_AT_POS_NOT", SkillResult.UrkDominionMemberAtPosNot),
        new(0x83, "URK_HOUSING", SkillResult.UrkHousing),
        new(0x84, "URK_HEALTH_MARGIN", SkillResult.UrkHealthMargin),
        new(0x85, "URK_MANA_MARGIN", SkillResult.UrkManaMargin),
        new(0x86, "URK_LABOR_POWER_MARGIN", SkillResult.UrkLaborPowerMargin),
        new(0x88, "URK_MAX_LEVEL", SkillResult.UrkMaxLevel),
        new(0x89, "URK_EXPEDITION_OWNER", SkillResult.UrkExpeditionOwner),
        new(0x8A, "URK_EXPEDITION_MEMBER", SkillResult.UrkExpeditionMember),
        new(0x8B, "URK_EXCEPT_PROGRESS_QUEST_CONTEXT", SkillResult.UrkExceptProgressQuestContext),
        new(0x8C, "URK_EXCEPT_READY_QUEST_CONTEXT", SkillResult.UrkExceptReadyQuestContext),
        new(0x8D, "URK_OWN_ITEM_NOT", SkillResult.UrkOwnItemNot),
        new(0x8E, "URK_LESS_ACTABILITY_POINT", SkillResult.UrkLessActabilityPoint),
        new(0x8F, "URK_OWN_QUEST_ITEM_GROUP", SkillResult.UrkOwnQuestItemGroup),
        new(0x90, "URK_LEADERSHIP_TOTAL", SkillResult.UrkLeadershipTotal),
        new(0x91, "URK_LEADERSHIP_CURRENT", SkillResult.UrkLeadershipCurrent),
        new(0x92, "URK_HERO", SkillResult.UrkHero),
        new(0x93, "URK_NOT_HERO", SkillResult.UrkNotHero),
        new(0x94, "URK_OWN_ITEM_COUNT", SkillResult.UrkOwnItemCount),
        new(0x96, "URK_HOUSE", SkillResult.UrkHouse),
        new(0x97, "URK_HOUSE_ONLY", SkillResult.UrkHouseOnly),
        new(0x98, "URK_DECO_LIMIT_EXPANDED", SkillResult.UrkDecoLimitExpanded),
        new(0x99, "URK_NOT_EXPANDABLE", SkillResult.UrkNotExpandable),
        new(0x9A, "URK_DOODAD_TARGET_FRIENDLY", SkillResult.UrkDoodadTargetFriendly),
        new(0x9B, "URK_DOODAD_TARGET_HOSTILE", SkillResult.UrkDoodadTargetHostile),
        new(0x9C, "URK_DOMINION_MEMBER", SkillResult.UrkDominionMember),
        new(0x9D, "URK_DOMINION_MEMBER_NOT", SkillResult.UrkDominionMemberNot),
        new(0x9E, "URK_CANNOT_USE_BUILDING_HOUSE", SkillResult.UrkCannotUseBuildingHouse),
        new(0x9F, "URK_TARGET_NOBUFF_TAG", SkillResult.UrkTargetNoBuffTag),
        new(0xA0, "URK_TARGET_NOBUFF_TAG_NO_TARGET", SkillResult.UrkTargetNoBuffTagNoTarget),
        new(0xA4, "URK_TARGET_MANA_LESS_THAN", SkillResult.UrkTargetManaLessThan),
        new(0xA5, "URK_TARGET_MANA_MORE_THAN", SkillResult.UrkTargetManaMoreThan),
        new(0xA6, "URK_TARGET_HEALTH_MORE_THAN", SkillResult.UrkTargetHealthMoreThan),
        new(0xA7, "URK_BUFF_TAG", SkillResult.UrkBuffTag),
        new(0xA8, "URK_FAMILY_ROLE", SkillResult.UrkFamilyRole),
        new(0xA9, "URK_LABOR_POWER_MARGIN_LOCAL", SkillResult.UrkLaborPowerMarginLocal),
        new(0xAA, "URK_HEIR_LEVEL", SkillResult.UrkHeirLevel),
        new(0xAB, "URK_IN_ZONE_GROUP", SkillResult.UrkInZoneGroup),
        new(0xAD, "URK_UNDER_WATER", SkillResult.UrkUnderWater),
        new(0xAE, "URK_OWN_APPELLATION", SkillResult.UrkOwnAppellation),
        new(0xAF, "URK_EQUIP_APPELLATION", SkillResult.UrkEquipAppellation),
        new(0xB1, "URK_FULL_RECHARGED_LABOR_POWER", SkillResult.UrkFullRechargedLaborPower),
        new(0xB2, "URK_EXPEDITION_MEMBER_NOT", SkillResult.UrkExpeditionMemberNot),
        new(0xB3, "URK_PIRATE_MEMBER_LIMIT", SkillResult.UrkPirateMemberLimit),
        new(0xB4, "URK_ACHIEVEMENT_COMPLETE", SkillResult.UrkAchievementComplete),
        new(0xB5, "URK_TARGET_ITEM_TAG", SkillResult.UrkTargetItemTag),
        new(0xB6, "URK_NO_TARGET_ITEM_TAG", SkillResult.UrkNoTargetItemTag),
        new(0xB7, "URK_DUAL", SkillResult.UrkDual),
        new(0xB8, "URK_NO_DUAL", SkillResult.UrkNoDual),
        new(0xB9, "URK_EXPEDITION_BATTLE", SkillResult.UrkExpeditionBattle),
        new(0xBA, "URK_NO_EXPEDITION_BATTLE", SkillResult.UrkNoExpeditionBattle),
        new(0xBB, "URK_NOT_IN_HOUSING_AREA", SkillResult.UrkNotInHousingArea),
        new(0xBC, "URK_DOMINION_COUNT_MORE", SkillResult.UrkDominionCountMore),
        new(0xBD, "URK_DOMINION_COUNT_LESS", SkillResult.UrkDominionCountLess),
        new(0xBE, "URK_PREMIUM_ARCHE_PASS", SkillResult.UrkPremiumArchePass),
        new(0xBF, "URK_ENABLE_ARCHE_PASS", SkillResult.UrkEnableArchePass),
        new(0xC0, "URK_GEAR_SCORE", SkillResult.UrkGearScore),
        new(0xC1, "URK_CONFLICT_ZONE_STATE", SkillResult.UrkConflictZoneState),
        new(0xC2, "URK_ITEM_ELEMENT_EVOLVING_EXP", SkillResult.UrkItemElementEvolvingExp),
        new(0xC3, "URK_NEED_ULC_ACTIVATE", SkillResult.UrkNeedUlcActivate),
        new(0xC4, "URK_CANNOT_USE_BY_ULC_ACTIVATE", SkillResult.UrkCannotUseByUlcActivate),
        new(0xC5, "URK_ITEM_LOOK_CHANGE_MAPPING", SkillResult.UrkItemLookChangeMapping),
        new(0xC6, "URK_ENABLE_ARCHE_PASS_WITH_TYPE", SkillResult.UrkEnableArchePassWithType),
        new(0xC8, "URK_ADD_ARCHE_PASS_POINT", SkillResult.UrkAddArchePassPoint),
        new(0xC9, "URK_TOWER_DEF_STEP", SkillResult.UrkTowerDefStep),
        new(0xCA, "URK_SOURCE_HEALTH_LESS_THAN", SkillResult.UrkSourceHealthLessThan),
        new(0xCB, "URK_SOURCE_HEALTH_MORE_THAN", SkillResult.UrkSourceHealthMoreThan),
    ];

    /// <summary>The symbol returns for a wire byte.</summary>
    public static string SymbolFor(byte wire) => Rows.FirstOrDefault(r => r.Wire == wire)?.Symbol ?? "URK_UNKNOWN";

    /// <summary>The ui_texts key the client UI looks up for a symbol.</summary>
    public static string KeyFor(string symbol) => "skill_" + symbol.ToLowerInvariant();
}
