// <auto-generated />
using System;
using AAEmu.Login.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AAEmu.Login.Migrations
{
    [DbContext(typeof(LoginDbContext))]
    partial class LoginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AAEmu.Login.Models.Database.GameServer", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("id");

                    b.Property<bool>("Hidden")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("hidden");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("host");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<ushort>("Port")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("port");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("game_servers", null, t =>
                        {
                            t.HasComment("Server list");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("AAEmu.Login.Models.Database.Update", b =>
                {
                    b.Property<string>("ScriptName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("script_name");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("datetime")
                        .HasColumnName("install_date");

                    b.Property<bool>("Installed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("installed");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.HasKey("ScriptName")
                        .HasName("PRIMARY");

                    b.ToTable("updates", null, t =>
                        {
                            t.HasComment("Table containing SQL update script information");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("AAEmu.Login.Models.Database.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<byte>("BanReason")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("ban_reason");

                    b.Property<bool>("Banned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("banned");

                    b.Property<ulong>("CreatedAt")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("email");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("last_ip");

                    b.Property<ulong>("LastLogin")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password")
                        .HasComment("Hashed password of the user");

                    b.Property<ulong>("UpdatedAt")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Username" }, "username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Account login information");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });
#pragma warning restore 612, 618
        }
    }
}
