namespace AAEmu.Game.Models.Game.Items;

public enum EquipmentItemSlotType : byte
{
    Head = 1,
    Neck = 2,
    Chest = 3,
    Waist = 4,
    Legs = 5,
    Hands = 6,
    Feet = 7,
    Arms = 8,
    Back = 9,
    Ear = 10,
    Finger = 11,
    Undershirt = 12,
    Underpants = 13,
    Mainhand = 14,
    Offhand = 15,
    TwoHanded = 16,
    OneHanded = 17,
    Ranged = 18,
    Ammunition = 19,
    Shield = 20,
    Instrument = 21,
    Bag = 22,
    Face = 23,
    Hair = 24,
    Glasses = 25,
    Reserved = 26,
    Tail = 27,
    Body = 28,
    Beard = 29,
    Backpack = 30,
    Cosplay = 31
}
