namespace AAEmu.Game.Models.Game.Formulas;

public enum UnitFormulaKind : byte
{
    // Commented Formula Kinds do not exist
    // TODO v.1.0
    MeleeCritical = 1,
    MeleeAntiMiss = 2,
    //MeleeDodge = 3,
    //MeleeBlock = 4,
    MeleeParry = 5,
    RangedCritical = 6,
    RangedAntiMiss = 7,
    //RangedDodge = 8,
    //RangedBlock = 9,
    SpellCritical = 10,
    SpellAntiMiss = 11,
    LevelDps = 12,
    LevelMana = 13,
    MaxHealth = 14,
    MaxMana = 15,
    HealthRegen = 16,
    ManaRegen = 17,
    Armor = 18,
    MagicResist = 19,
    Facet = 20,
    MeleeDpsInc = 21,
    Str = 22,
    Dex = 23,
    Sta = 24,
    Int = 25,
    Spi = 26,
    Fai = 27,
    RangedDpsInc = 28,
    SpellDpsInc = 29,
    CastingTolerance = 30,
    PersistentHealthRegen = 31,
    PersistentManaRegen = 32,
    BaseMissPercent = 33,
    KillExp = 34,
    MeleeCriticalBonus = 35,
    RangedCriticalBonus = 36,
    SpellCriticalBonus = 37,
    RangedParry = 38,

    // TODO v.1.2
    IncomingMeleeDamageAdd = 39,
    IncomingRangedDamageAdd = 40,
    IncomingSpellDamageAdd = 41,
    HealCritical = 42,
    HealDpsInc = 43,
    HealCriticalBonus = 44,
    Block = 45,
    Dodge = 46,

    // TODO v.5.0
    Mass = 47,
    SteeringSpeed = 48,
    ReverseVelocity = 49,
    MeleeDynamicNormalizable = 50,
    RangedDynamicNormalizable = 51,
    MagicDynamicNormalizable = 52,
    HealDynamicNormalizable = 53,
    DefenceDynamicNormalizable = 54,
    MusicDynamicNormalizable = 55,
    unk59 = 59,
    unk60 = 60,
    unk61 = 61,
    unk63 = 63,
    unk64 = 64,
    unk65 = 65,
    unk66 = 66
}
