name: Build & Unit Test

on:
  push:
    branches: [master, develop]
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Scripts Compile
        run: dotnet run --configuration Release --no-build --project AAEmu.Game/AAEmu.Game.csproj compiler-check
      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage
      - name: Test
        run: dotnet-coverage collect "dotnet test AAEmu.UnitTests --configuration Release --no-build" -f cobertura -o AAEmu.UnitTests/TestResults/coverage.cobertura.xml
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./AAEmu.UnitTests/TestResults/coverage.cobertura.xml
