name: Publish Wiki

on:
  push:
    branches:
      - develop
    paths:
      - Docs/wiki/**
  workflow_dispatch:

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish docs wiki folder to GitHub Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v5.0.3
        with:
          token: ${{ github.token }}
          path: Docs/wiki/
